### ISSUE TITLE
Undocumented AHF Properties

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/docs#101]
Raised originally in #81 by @markgif 

I have since also found out about two undocumented command line parameters for enabling the use of Antenna House:

ahf.dir
The directory where AH is installed.

ahf.cmd
The path to AHFCmd.exe in that directory. (I'm using Windows 7, not sure about other OSes)

**Comment by jelovirt** [comment]
The `ahf.dir` doesn't exist. The other property is `axf.cmd` and that specified the AHF executable that is used to run AHF from the command line.

**Comment by markgif** [comment]
I have two questions related to this.

1. How does the OT access Antenna House when you tell it to use it with 
the command line parameter? I assume the OT does not use this AH command 
line executable. What does it use?

2. Is the answer different for 1.8 and 2.x OT versions?

Thanks,
Mark

**Comment by drmacro** [comment]
The OT uses the command line executable. This is in pdf2/build_axf.xml:
```
<exec executable="${axf.cmd}" resultproperty="errCode" logerror="true">
      <arg value="-d"/>
      <arg value="${pdf2.temp.dir}/topic.fo"/>
      <arg value="-o"/>
      <arg value="${outputFile}"/>
      <arg value="-p"/>
      <arg value="${axf.formatter.output-format}"/>
      <arg value="-extlevel"/>
      <arg value="4"/>
      <arg value="-peb"/>
      <arg value="1"/>
    </exec>
```

**Comment by markgif** [comment]
Well I'll be darned! That's the way I've done it in a couple plugins and 
I figured I was doing a hack. I had the idea there would be some Java 
class the OT would access or something. No wonder I could not find it 
when I looked for it. Thanks Eliot.

Mark
