### ISSUE TITLE
Necessary to Escape Backslashes in Properties

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/docs#102]
Raised in #81 by @markgif

> I had to escape the backslashes by repeating them: \\
> 
> No quotes around the path were needed, even though there are spaces in it. 
> Adding quotes around the path makes it fail. 

(I'm using Windows 7, not sure about other OSes)

You have to escape the backslashes with \\, even though the path to the ditamap does not have to use escaped backslashes (arcane!). So the following command seems to work with OT 1.7.5 without the local.properties file as described earlier:

```
ant -Dargs.input=C:\path\to\map\my.ditamap -Dtranstype=my-pdf -Dpdf.formatter=ah 
    -Dahf.dir=C:\\Program Files\\Antenna House\\AHFormatterV62 
    -Dahf.cmd=C:\\Program Files\\Antenna House\\AHFormatterV62
```

**Comment by jelovirt** [comment]
Nothing arcane about it, backslash is an escape character. The file format is described in http://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader-
