### ISSUE TITLE
Explain HTML5 parameter extension points

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#104]
Some parameters are missing in [XSLT-parameter extension points](http://www.dita-ot.org/dev/extension-points/plugin-extension-points-xslt-parameters.html), which are defined in the [org.dita.html5/plugin.xml](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.html5/plugin.xml).

```xml
<extension-point id="dita.conductor.html5.param" name="HTML5 XSLT parameters"/>
<extension-point id="dita.conductor.html5.toc.param" name="HTML/XSLT XSLT parameter"/>
```

**Comment by infotexture** [comment]
* [Extensions in `org.dita.html5`](http://www.dita-ot.org/dev/extension-points/extension-point-org.dita.html5.html)
* [XSLT-import extension points](http://www.dita-ot.org/dev/extension-points/plugin-extension-points-xslt-import.html)
* [XSLT-parameter extension points](http://www.dita-ot.org/dev/extension-points/plugin-extension-points-xslt-parameters.html)
