### ISSUE TITLE
Update information on “DITA for Print”

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#108]
A new edition of Leigh White’s _DITA for Print_ book is due out soon.

The information in the [Resources for custom PDF plug-ins](http://www.dita-ot.org/dev/dev_ref/pdf-customization-resources.html) topic should be updated for the new edition to correspond with the latest version of the book.

**Comment by infotexture** [comment]
Per discussion in the October docs call, this task can be completed via the [Edit this page!](https://www.oxygenxml.com/webapp-demo-aws/app/oxygen.html?url=github%3A%2F%2FgetFileContent%2Fdita-ot%2Fdocs%2Fdevelop%2Fdev_ref%2Fpdf-customization-resources.dita&ditamap=github%3A%2F%2FgetFileContent%2Fdita-ot%2Fdocs%2Fdevelop%2Fuserguide-book.ditamap) link in the topic footer.

**Comment by infotexture** [comment]
@leighw Are you able to provide updated information on the new edition yet?

**Comment by leighw** [comment]
Unfortunately, my publisher can no longer confirm that the book will be available in November for the 2.4 release, though he still intends to try. If it doesn't make it, he is hopeful that the delay will not be too great...early to mid December.

**Comment by infotexture** [comment]
@leighw OK, good to know. We can still revise the information on the book to point to the upcoming edition without stating a specific release date. That way the DITA-OT 2.4 docs would let users know that a new version is on the way.

If you have suggestions for how you'd like to phrase that, feel free to propose changes via the [Edit this page!](https://www.oxygenxml.com/webapp-demo-aws/app/oxygen.html?url=github%3A%2F%2FgetFileContent%2Fdita-ot%2Fdocs%2Fdevelop%2Fdev_ref%2Fpdf-customization-resources.dita&ditamap=github%3A%2F%2FgetFileContent%2Fdita-ot%2Fdocs%2Fdevelop%2Fuserguide-book.ditamap) link in the topic footer.

**Comment by infotexture** [comment]
@leighw I updated the [Resources for custom PDF plug-ins](http://www.dita-ot.org/dev/dev_ref/pdf-customization-resources.html) topic with [information on the second edition of your book](http://www.dita-ot.org/dev/dev_ref/pdf-customization-resources.html#ID__dita-for-print).

See https://github.com/dita-ot/docs/commit/bf268f8b7adc03c1bd7ff310ddd8ca41442575db for the changes, add let us know if there's anything else we should change — or use the the [Edit this page!](https://www.oxygenxml.com/webapp-demo-aws/app/oxygen.html?url=github%3A%2F%2FgetFileContent%2Fdita-ot%2Fdocs%2Fdevelop%2Fdev_ref%2Fpdf-customization-resources.dita&ditamap=github%3A%2F%2FgetFileContent%2Fdita-ot%2Fdocs%2Fdevelop%2Fuserguide-book.ditamap) link in the topic footer to change it yourself.
