### ISSUE TITLE
Add list of third-party software used by DITA-OT

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#120]
The DITA-OT docs should include a list of third-party software with version numbers and license information, similar to the list provided for [IntelliJ IDEA](https://confluence.jetbrains.com/display/IDEADEV/Third-Party+Software+Used+by+IntelliJ+IDEA+2016.3).

**Comment by jelovirt** [comment]
Project | Version | License 
--------|---------|---------
Ant| 1.9.7 | [Apache License 2.0]
Batik | 1.8 | [Apache License 2.0]
Apache Commons Codec | 1.10 | [Apache License 2.0]
Apache Commons IO | 2.5 | [Apache License 2.0]
Guava | 19.0 | [Apache License 2.0]
ICU4J | 57.1 | [ICU License]
Saxon | 9.1.0.8 | [Mozilla Public License 1.0]
Xerces | 2.11.0 | [Apache License 2.0]
XML Apis | 1.4.01 | [Apache License 2.0]
XML Resolver | 1.2 | [Apache License 2.0]
FOP | 2.1 | [Apache License 2.0]
Apache Commons Logging | 1.0.4 | [Apache License 2.0] 
Avalon Framework | 4.3.1 | [Apache License 2.0]

[ICU License]: http://source.icu-project.org/repos/icu/icu/tags/release-57-1/LICENSE)
[Mozilla Public License 1.0]: https://www.mozilla.org/media/MPL/1.1/index.0c5913925d40.txt)
[Apache License 2.0]: https://www.apache.org/licenses/LICENSE-2.0.txt)

**Comment by xephon2** [comment]
Gradle?

**Comment by jelovirt** [comment]
* Gradle is not a dependency, it's just the build tool.
* Log4J is not used
* Xalan is not used

**Comment by jelovirt** [comment]
Should we split the list to core and plugin dependencies? https://github.com/dita-ot/docs/issues/120#issuecomment-262830658 has dependencies for both core DITA-OT and PDF2 plugin.

**Comment by infotexture** [comment]
@jelovirt Thanks for providing the info. 

I think splitting the list into core and plugin dependencies makes sense.

**Comment by jelovirt** [comment]
@infotexture update the table.
