### ISSUE TITLE
Move new "Third-party software" topic

### ISSUE THREAD

**Issue by robander** [dita-ot/docs#124]
As discussed in the contributor call today - my (probably non-typical) approach when finding almost any new open source project is to look for licensing info. That's in tiny print on the bottom of every doc page right now. I'm used to seeing something a bit more obvious in the main page or TOC. One idea would be to have a "License" or "Legal" item at the top of the TOC, which would take you to our simple licensing info, and to the new third-party list (probably as a sub-topic). Don't know if that's the best organization, just one idea, but it would be good to make the new topic easier to find.

**Comment by infotexture** [comment]
I'll create a new top-level **License** item with a link to the Apache license and add _Third-party software_ as a sub-topic.
