### ISSUE TITLE
Is the --filter command path absolute or relative ?

### ISSUE THREAD

**Issue by lionelmoi** [dita-ot/docs#128]
I think this should be explicitly explained in the [dita command arguments page](http://www.dita-ot.org/dev/parameters/dita-command-arguments.html).

**Comment by infotexture** [comment]
I'll leave the original question to @jelovirt, but we should probably take this opportunity to review parameter descriptions w/r/t their support for absolute vs. relative paths and provide guidance on the preferred method(s) for specifying absolute paths for parameters like `args.[ftr|hdf|hdr]` that require them.

**Comment by infotexture** [comment]
For related discussion, see dita-ot/dita-ot#2593.

**Comment by jelovirt** [comment]
IIRC, when you pass `args.filter` as an Ant property, it's assumed it's an absolute file and if it happens to be relative, it's resolved against DITA-OT base directory (for backwards compatibility). If you pass `--filter` to CLI, relative paths are resolved against the current directory.
