### ISSUE TITLE
[Bug] dita --install syntax is incorrect

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/docs#129]
The 2.4 docs now give the following syntax:
```
dita-ot-dir/bin/dita --install=plug-in-zip
```
But this does not work (at least in 2.4.2). You must omit the = sign:
```
dita-ot-dir/bin/dita --install plug-in-zip
```

**Comment by infotexture** [comment]
Looks like you're right, good catch.

The command-line help that appears when you run `dita --help` also shows the equals sign for both the `--install` and `--uninstall` options, so it looks like the `Main.java` source code needs to be changed on  [lines 1268, 1276 & 1278](https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/invoker/Main.java#L1268-L1278).
