### ISSUE TITLE
Document new Java API for 2.5

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#131]
Pull request https://github.com/dita-ot/dita-ot/pull/2604 adds a simple API to invoke DITA-OT from Java. The _Developer Reference_ and related documentation should be extended per @jelovirt's recommendations:

> As a developer, my preference would be to ship Javadoc with our HTML documentation and have a tutorial topic on how to use it. The API is small, so a single topic should be enough.

**Comment by jelovirt** [comment]
The goal of adding the new Java API to DITA-OT is to allow users to embed DITA-OT more easily to Java programs. When using the API, programmers don't need to know or care that DITA-OT uses Ant, they can just use Java. The `ant` shell script will handle the classpath setup for the user, but when using the API the classpath setup should be done as part of normal classpath configuration.

Example usage:

```java
// Create reusable processor factory with DITA-OT base directory and temporary directory
ProcessorFactory pf = ProcessorFactory.newInstance(ditaDir);
pf.setBaseTempDir(tempDir);

// Create a processor using the factor and configure the processor
Processor p = pf.newProcessor("html5")
    .setInput(mapFile)
    .setOutputDir(out)
    .setProperty("nav-toc", "partial");

// Run conversion
p.run();
```

By default, running DITA-OT via the API will generate a debug log to temporary directory; a custom SLF4J logger can be used to access log.

By default, processor will clean the temporary directory, but this can be disabled for cases where the processor failed.
