### ISSUE TITLE
plugin-addgeneratedtext references deprecated getString template

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/docs#137]
Replace the getString template with getVariable:
```
<xsl:call-template name="getVariable">
  <xsl:with-param name="id" select="'Another String'"/>
</xsl:call-template>
```

Might want also to mention (perhaps elsewhere as "stuff your XSL files need") that the XSL file needs:
```
<xsl:import href="plugin:org.dita.base:xsl/common/dita-utilities.xsl"/>
<xsl:import href="plugin:org.dita.base:xsl/common/output-message.xsl"/>
<xsl:variable name="msgprefix">-something-</xsl:variable>
```

Only the first line should probably be required, but the toolkit throws errors if:
* you include dita-utilities.xsl without output-message.xsl 
* you include output-message.xsl without defining the (deprecated) msgprefix variable

**Comment by infotexture** [comment]
Previously reported as #133.

**Comment by infotexture** [comment]
@shaneataylor Closing this since your PR #138 resolves the main issue. 

(Feel free to submit a separate PR if you'd like to address the additional suggestions.)
