### ISSUE TITLE
Missing description of property cli.color

### ISSUE THREAD

**Issue by robander** [dita-ot/docs#145]
The topic about `configuration.properties` doesn't list one new option:
http://www.dita-ot.org/2.5/parameters/lib-configuration-properties.html

The topic covers every property that ships in that configuration file apart from a new one:
`cli.color=true`

I'm pretty sure the values are `true` and `false`, and that this is a property that can turn on/off coloring for warnings in the command line output, but it would be good for @jelovirt to verify that. (As I recall it doesn't work on Windows, otherwise I'd be testing it before opening this issue.)

**Comment by jelovirt** [comment]
Yes, the value space is `true` or `false`.
