### ISSUE TITLE
Where is the DITA OT Slack channel?

### ISSUE THREAD

**Issue by markgif** [dita-ot/docs#146]
I heard this Slack channel exists but searches have proved fruitless. Can you guide me? And maybe add it to the home page? Thanks

**Comment by robander** [comment]
It's at: https://dita-ot.slack.com/

The only real trick is that you have to be invited, and to be invited you have to contact one of the admins (currently myself and @jelovirt ) with your preferred email.

**Comment by infotexture** [comment]
After discussions in the [July contributors call](https://github.com/dita-ot/dita-ot/wiki/Meeting-minutes-2017-07-06), we plan to set up a public form that users can fill out to join our Slack team.

Once https://github.com/dita-ot/dita-ot/issues/2745 is resolved, we'll add a link to the project website and documentation.

**Comment by jelovirt** [comment]
dita-ot/dita-ot#2745 has been closed and Slackin is running at http://slack.dita-ot.org/

**Comment by jelovirt** [comment]
@infotexture Should we add link to http://slack.dita-ot.org/ in web site header navigation, under _Collaboration_? Maybe with link text _Project Slack_ or just _Slack_ because we have both code and documentation channels there.

**Comment by infotexture** [comment]
Links to https://dita-ot.slack.com and the invitation form at http://slack.dita-ot.org were added to the [Contributing](http://www.dita-ot.org/contributing) page with dita-ot/dita-ot.github.io@d607c45, but it makes sense to include the invitation link in the **Collaboration** menu.
