### ISSUE TITLE
Rename error level "Informational" to "information"

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#153]
The error level `Informational` should be renamed to `information` or `info`. There's no `Informational` error level, at least in [org.apache.tools.ant.types.LogLevel](https://ant.apache.org/manual/api/org/apache/tools/ant/types/LogLevel.html) or [org.apache.log4j.Level](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Level.html).

I meant [DITA-OT error messages](http://www.dita-ot.org/dev/user-guide/DITA-messages.html).

**Comment by infotexture** [comment]
The severity levels used here are apparently based on the standard syslog severity levels as defined by [RFC 5424](https://tools.ietf.org/html/rfc5424), which explicitly include `Informational`, so it's not really wrong.

That level is commonly abbreviated as `INFO` in [Log4j](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Level.html) and elsewhere, and the abbreviated form may be more intuitively understandable to non-native readers, so it's probably still worth clarifying.
