### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/tools/ant/launch/Launcher : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by nicolasb-git** [dita-ot/docs#157]
Hi,

I get this error Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/tools/ant/launch/Launcher : Unsupported major.minor version 52.0

My Java version is:
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

In documentation it is written "Ensure that you have a Java Runtime Environment (JRE) or Java Development Kit (JDK), version 8 or later installed."

How do I bypass this?

BR
Nicolas

**Comment by infotexture** [comment]
For support questions, please use the community support channels listed at [dita-ot.org/contributing](http://www.dita-ot.org/contributing).
