### ISSUE TITLE
Update dita command example

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#158]
This snippet from `/docsrc/samples/ant_sample/dita-cmd.xml` should use the new propertyfile notation as explained on [Building output using the dita command](http://www.dita-ot.org/2.5/user-guide/build-using-dita-command.html).

```xml
<macrodef name="dita-cmd">
  <attribute name="input"/>
  <attribute name="format"/>
  <attribute name="propertyfile"/>
  <sequential>
    <exec executable="${dita.dir}/bin/dita">
      <arg line="-i @{input} -f @{format} -propertyfile @{propertyfile}"/>
    </exec>
  </sequential>
</macrodef>
```

should be changed to

```xml
<macrodef name="dita-cmd">
  <attribute name="input"/>
  <attribute name="format"/>
  <attribute name="propertyfile"/>
  <sequential>
    <exec executable="${dita.dir}/bin/dita">
      <arg line="-i @{input} -f @{format} --propertyfile=@{propertyfile}"/>
    </exec>
  </sequential>
</macrodef>
```

**Comment by infotexture** [comment]
@xephon2 Thanks, good catch. 👍 

We try to use the GNU double-hyphen syntax for CLI options throughout the docs, so I'll also switch to `--input` and `--format` here.
