### ISSUE TITLE
Improve Customizing Generated Text Topic

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/docs#165]
Proposed changes include:

- Change to task.
- Break out use cases to individual subtopics.
- Recommend best practice that generated text be its own plugin, and that other customizations set dependency on the generated text plugin (better than reimplementing the same generated text for  different output types).

**Comment by infotexture** [comment]
See #31 & https://github.com/dita-ot/dita-ot/pull/2789.

@robander Not sure what implications the changes in https://github.com/dita-ot/dita-ot/pull/2789 will have on best practices w/r/t customization of generated text.

Any thoughts on that?

**Comment by robander** [comment]
Not certain of impacts - probably none for the common case, may want to cover the edge case but may not?

Old practice: if you want to _change_ text for any language, the variable is already there, so you have to create a new variable in that language and add as plugin.

New: 
1. for the common case (string exists for language `xy`, you're changing), practice is the same. 
2. There are now a few cases where "text" (really, variables) are common to all or nearly all languages. For those, you can create you own custom no-language variable, using the same patterns as you would today for a specific language. Or, you can create a custom version for a specific language. For example, there is a now a common string `<str name="OpenQuote">“</str>`. You can override that for every language, or you can create one in a custom German version to just update for German.

Not sure if that will all make sense...
