### ISSUE TITLE
New doc topic: changes during preprocess

### ISSUE THREAD

**Issue by robander** [dita-ot/docs#17]
The DITA-OT preprocess adds several items that later rendering steps can make use of, and which might change the content to be not-quite-pure DITA. This can simplify the shipped rendering in many ways, such as eliminating any need to process a DITAVAL file to support flagging.

We should document these changes so that developers of new transform types are aware of them. This lets them take advantage of the updates, and also lets them know what has changed that might not be "pure DITA".

I don't think we need to list all of the stuff that is already covered / assumed, such as "conref is resolved". Offhand the things I know of that we need to document are:
- Processing instructions added by "topicpull" when text is pulled into a link or xref element. This lets later steps distinguish between generated text and authored text. Authored text should always be preserved, but a rendering step may want to change the format of generated text; for example, PDF processing replaces generated "Figure N" text with a different figure number and possibly with a page number.
- Flagging information is added using pseudo-foreign specializations (this may already be documented in the flagging documentation?)

Also considering an update that would add things like `@dita-ot:href` in this newly opened issue; if we move forward it would need to be documented as well: https://github.com/dita-ot/dita-ot/issues/1837

**Comment by robander** [comment]
Today noticed something that isn't exactly the same issue - not sure if this should be in a different topic. We make changes during preprocess that could cause the "normalized" DITA to be invalid against the original schema, often due to specialization. I noticed this today with a subjectScheme map; our preprocess cascades attributes, such as `@type` or `@toc`. The subject scheme has several elements that disallow these attributes - for example `<enumerationdef>` does not allow `@type` and `<attributedef>` does not allow `@toc`. After the preprocess, these attributes are present due to the cascade, even though invalid. This could happen with any specialized map, just noting subject scheme because it's an OASIS-defined specialization in use lots of places.

Of course, within the DITA-OT processing pipeline, this is not a problem - the attributes are ignored because they are meaningless in this map - but it does mean the processing fragment is not quite "pure DITA".

**Comment by infotexture** [comment]
@robander Would it make sense to combine this with the discussion of map-first preprocessing for #136 and contrast the two different approaches?

The @dita-ot/docs team will need significant input for both of these issues.
