### ISSUE TITLE
Explain how to use custom logger with dita command

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#174]
The topic [Log files](http://www.dita-ot.org/dev/user-guide/log-files.html) says:

> You also can use other Ant loggers; see the Ant documentation for more information.

- This statement should include a link to [Listeners & Loggers](https://ant.apache.org/manual/listeners.html).
- It should be explained, how to setup a custom logger with the dita command. Probably this is not possible ATM, because there is no `--logger` parameter for the dita command defined (or at least it is not documented). In that case, a statement like the following would be helpful:
  > Currently you cannot define a custom logger when using the dita command.

**Comment by infotexture** [comment]
> Currently you cannot define a custom logger when using the dita command.

@jelovirt Is that correct?

**Comment by shaneataylor** [comment]
You can do this prior to running the dita command:
```export ANT_ARGS="-logger org.apache.tools.ant.XmlLogger"```

With a custom XSLT stylesheet for the log file, I have logs that I can view in the browser with highlighting and counts for warnings and errors, with expandable/collapsible sections of the log.

**Comment by xephon2** [comment]
Thank you @shaneataylor, this works. I created a new PR https://github.com/dita-ot/docs/pull/176 and explained how that works for the `dita` command and for Ant. I used the **org.apache.tools.ant.listener.AnsiColorLogger** in the example, because the mentioned **org.apache.tools.ant.XmlLogger** is probably more relevant for advanced users.
