### ISSUE TITLE
Wrong root element in messages example

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#186]
The page [Adding new diagnostic messages](http://www.dita-ot.org/dev/dev_ref/plugin-messages.html) gives the following example for a **messages.xml**:

```xml
<dummy>
  <!-- See resources/messages.xml for the details. -->
  <message id="PrefixNumberLetter" type="error-severity">
    <reason>Message text</reason>
    <response>How to resolve</response>
  </message>
</dummy>
```

This is not correct. The given DTD `dita-ot/resources/messages.dtd` defines a root element called `<messages>`, not `<dummy>`:

```xml
<!ELEMENT messages (message)+ >
<!ELEMENT message (reason, response) >
<!ATTLIST message id ID #REQUIRED >
<!ATTLIST message type (FATAL|ERROR|WARN|INFO|DEBUG) #REQUIRED >
<!ELEMENT reason (#PCDATA) >
<!ELEMENT response (#PCDATA) >
```

The example should be changed to:

```xml
<messages>
  <!-- See resources/messages.xml for the details. -->
  <message id="PrefixNumberLetter" type="error-severity">
    <reason>Message text</reason>
    <response>How to resolve</response>
  </message>
</messages>
```

**Comment by jelovirt** [comment]
The root element in this case makes no difference, because it's not actually read by the integrator process. So technically the example code is correct and works. However, for consistency it's probably better to change it to use `<messages>`.

**Comment by infotexture** [comment]
👍 Makes sense.

@xephon2 PR welcome. If you'd like to submit one, it should target the `hotfix/3.0.1` branch.

**Comment by infotexture** [comment]
Not strictly related to this issue, but there are several other topics where the docs still suggest `<dummy>` root elements in plug-in examples. 

Cases like [Adding a Java library](http://www.dita-ot.org/dev/dev_ref/plugin-javalib.html) should probably refactored to replace the dummy file reference with the `ant.import` approach per [Adding a new target to the Ant build process](http://www.dita-ot.org/dev/dev_ref/plugin-anttarget.html):

> **Tip:** Earlier versions of DITA-OT use the `dita.conductor.target.relative` to call a wrapper file with a dummy task that imports the Ant project file. This approach is still supported for backwards compatibility, but the simpler `ant.import` approach described above should be used for all new customizations.

In other cases, `<dummy>` root elements are used to wrap new `<param>` elements, as in:

* [Adding parameters to existing XSLT steps](http://www.dita-ot.org/dev/dev_ref/plugin-xsltparams.html)
* [XSLT-parameter extension points](http://www.dita-ot.org/dev/extension-points/plugin-extension-points-xslt-parameters.html)

I assume @jelovirt's [explanation above](https://github.com/dita-ot/docs/issues/186#issuecomment-346321247) also applies here, so it may not be critical, but I wonder whether it's worth explaining that the root element is ignored in these cases (and need not be literally named `<dummy>`)?

**Comment by jelovirt** [comment]
Yes, they don't have to be `dummy`

**Comment by lionelmoi** [comment]
Would it be possible to actually validate such files against the DTD?

**Comment by jelovirt** [comment]
The files can be validated, when would you want to do that? E.g. a DTD cannot really be written for XSLT.

**Comment by lionelmoi** [comment]
Maybe during the plugin installation process?

**Comment by jelovirt** [comment]
But why would we want to validate them? To make sure plugin authors haven't made a mistake and if there are validation issues, make the integration process fail?

**Comment by lionelmoi** [comment]
I actually don't mind ignoring the name of the root because I know it is not an issue. 

The issue may be for new developers. Having a root that has no relationship to the rest of the content may not help understanding the context.

Following this idea, yes it would be interesting to at least warn during the install of new plugins. Failing may be a bit over the top.

Message could be something like `Root element of {file} is not <message>. This may be confusing for new users of your plugin. Consider renaming root.`

**Comment by jelovirt** [comment]
But new users of the plugin should never go and read the message file. So in that sense this is a poor example. There are actually very few files plugin *users* actually would open and read.

**Comment by lionelmoi** [comment]
I agree; I should have said `developers` or `integrators`.

Remember, I'm talking about a message displayed during install. Not somethign every user does, only advanced users. 

I those users are the owner of the plugin they can change the file, and if they're not they can report it to the owner of the plugin, or submit a PR.

**Comment by xephon2** [comment]
I think, the docs should explain, that a grammar file (e.g. for plugin.xml or messages.xml) exists, and that he should validate the file with that grammar. It is not important, to explain the user, that he technically could rename the root element. It is more important and much easier to show him a solution that works and how he can make sure that his work is correctly done, than explaining to him "technically it is not important, how you should name your root element in this case here, because...". The OT is extremely hard to understand for starters and those little optimizations make it easier for the user to dive into it. The docs are the ❤️ of the toolkit.

**Comment by xephon2** [comment]
@keberlein There is a very old comment from you in this file:

```xml
<draft-comment author="Kristen Eberlein" time="31 March 2013">What advice should we give users to prevent them from using a message number and letter combination that is already used by the DITA-OT? If that happens, what is the result?</draft-comment>
```

If the `@id` is identical, the imported **messages.xml** would override the default one. I'll explain that also in the PR.

**Comment by xephon2** [comment]
I cannot refer to the **messages.dtd** as suggested, because it has been removed from DITA-OT 3.0.
