### ISSUE TITLE
Add topic on coding conventions for plugins

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#191]
Per 2018-01-27 Slack [discussion](https://dita-ot.slack.com/archives/C02UXQF5G/p1517050382000024), content should include:

> * use custom `<pipeline>` with `<xslt>` module instead of build-in Ant `<xslt>` task
> * use `<ditafileset>` to select files for processing instead of build-in `<fileset>` that selects files from temporary directory
> 
> Or for XLST stylesheets
> 
> * use `plugin` URI scheme in `<xsl:import>` and `<xsl:include`> to reference files in depended plugins

Content provided by @jelovirt, to be revised by @infotexture & reviewed by @robander.

**Comment by shaneataylor** [comment]
Just discovered: With the recent upgrade to Saxon-HE 9.8, plugins with XSLT templates specifying version 1.0 will fail with the message "XSLT 1.0 compatibility mode is not available in this configuration". Need to change `<xsl:stylesheet version="1.0"` to at least ``<xsl:stylesheet version="2.0"``

Suggests a convention that all plugins specify version 2.0 at a minimum.

**Comment by infotexture** [comment]
👍 Good point, I'll add that to the topic draft and the 3.0 migration topic.

**Comment by infotexture** [comment]
@jelovirt & @robander The [first draft of the topic](http://www.dita-ot.org/dev/topics/plugin-coding-conventions.html) based on initial input is available for review.

Shall we add an XSLT 2.0 recommendation per [Shane's comment](https://github.com/dita-ot/docs/issues/191#issuecomment-361099103) even though the Saxon-HE update in 3.0.2 restores XSLT 1.0 compatibility?

**Comment by jelovirt** [comment]
Yes, We should push XSLT 2.0 because Saxon can remove XSLT 1.0 support in the next minor release and we'd again be in the same situation.

**Comment by infotexture** [comment]
I added the XSLT2 recommendation to the [current draft of the topic](http://www.dita-ot.org/dev/topics/plugin-coding-conventions.html) with 4d054db, so I think we can probably close this issue and update the topic later if we have any other ideas.

The only thing discussed here that isn't covered yet is the catalog reference suggested by @robander:

> Unless that's changing in 3.1 (so that our pipeline XSLT task automatically adds the catalog) we should add this line to the example and also note it's required: 
`<xmlcatalog refid="dita.catalog"/>`

— but it looks like the changes in https://github.com/dita-ot/dita-ot/commit/ddfc3e8bd000e299788b5e5c4f2cb765dd934258 may mean that's no longer necessary.

@jelovirt Do I understand that correctly?

**Comment by jelovirt** [comment]
@infotexture Yes, this should be the case. A '<xmlcatalog>' should only be used if you wish to use an alternative catalog.

**Comment by infotexture** [comment]
👍 Thanks, closing…
