### ISSUE TITLE
Order of download kits

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#198]
Here:
http://www.dita-ot.org/download

We have an order like this:
2.5
2.5.1
2.5.2
2.5.3
2.5.4

and I would like to see it reversed, to bring the latest releases (in this case 2.5.4) to the top of the stack.
Because I keep making mistakes and downloading DITA OT 2.5 believing it's the latest release.

If you look at the "Legacy versions" table further down, it is properly sorted with recent versions before the old.

**Comment by infotexture** [comment]
@raducoravu The **Download** page is not part of the docs. For future reference, we have a separate tracker for website issues at https://github.com/dita-ot/dita-ot.github.io/issues.

_(No need to re-create this there though.)_

My intention was to use each minor release as a group title, with the series of associated maintenance releases below, but I see how the row headers may attract attention, so I'll test a few alternatives.

**Comment by raducoravu** [comment]
Right, those headers with slightly different color somehow signal to me that is the most important kit in the column.

**Comment by raducoravu** [comment]
👍
