### ISSUE TITLE
Certain extension points are not explained anywhere 

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#20]
For example all the extension points in the pdf2 plugin:

```xml
<extension-point id="org.dita.pdf2.xsl.topicmerge" name="PDF2 topic merge XSLT import"/>
<extension-point id="depend.org.dita.pdf2.format.pre" name="Formatting pre-target"/>
<extension-point id="depend.org.dita.pdf2.format" name="Formatting target"/>
<extension-point id="depend.org.dita.pdf2.format.post" name="Formatting post-target"/>
<extension-point id="org.dita.pdf2.catalog.relative" name="Configuration XML catalog"/>
<extension-point id="dita.conductor.pdf2.param" name="PDF XSLT parameters"/>
```
I cannot find them anywhere in the [docs](http://www.dita-ot.org/2.0/). Actually I cannot find in the docs a list with all extension points anymore.

**Comment by infotexture** [comment]
Looks like the old `extension-points.dita` topic was disabled for v1.5.4 w/ commit dita-ot/dita-ot@7d0f127. The file was later removed along with other unreferenced files for #15.

Most of the information in that topic was included in the new [plug-in section](http://www.dita-ot.org/2.0/dev_ref/plugins-overview.html) of the _Developer Reference_, in topics like [Extending the XML Catalog](http://www.dita-ot.org/2.0/dev_ref/plugin-xmlcatalog.html), which mentions `org.dita.pdf2.catalog.relative`.

But that can be tough to find, so it would be good to have a complete list of all extension points in one place, and point to additional information on each where available.

We might want to consider generating that list like we do with the messages and Ant parameters.

Any other opinions or suggestions?

**Comment by keberlein** [comment]
Roger, check out the topics in the attached ZIP. These were reworks
    of the content that I started a long time back, might be useful ...
    
    
    Best,
      Kris
      
      Kristen James Eberlein
      Chair, OASIS DITA Technical Committee
      Principal consultant, Eberlein Consulting
      www.eberleinconsulting.com
      +1 919 682-2290; kriseberlein (skype)
      
    
    On 4/1/2015 10:58 AM, Roger Sheen
      wrote:
    
    
      Looks like the old extension-points.dita topic
        was disabled for v1.5.4 w/ commit dita-ot/dita-ot@7d0f127. The
        file was later removed along with other unreferenced files for #15.
      Most of the information in that topic was included in the new plug-in
          section of the Developer Reference, in topics
        like Extending
          the XML Catalog, which mentions org.dita.pdf2.catalog.relative.
      But that can be tough to find, so it would be good to have a
        complete list of all extension points in one place, and point to
        additional information on each where available.
      We might want to consider generating that list like we do with
        the messages and Ant parameters.
      Any other opinions or suggestions?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by jelovirt** [comment]
I think we should generate the list of extension points like we do for messages and will for parameters. Then, use pushconref to add additional descriptions.

**Comment by raducoravu** [comment]
Maybe each extension point would have some metadata embedded in the plugin.xml explained what it could be used for.

**Comment by jelovirt** [comment]
Each extension already has a [`@name`](http://www.dita-ot.org/2.0/dev_ref/plugin-newextensions.html) attribute, which is basically equivalent to `@desc`. We're unfortunately stuck with the old name, even though `@desc` would be more descriptive.

**Comment by infotexture** [comment]
OK, I'll make that change when I merge in the WIP from @keberlein for #21.

**Comment by keberlein** [comment]
Just as long as the topics are reviewed for quality/technical accuracy/etc. They'll need some additional work for sure; I had not completed work on them when I last touched them who knows how long ago. (But if they are helpful, great.)

Kris

**Comment by infotexture** [comment]
A list of all extension points is now generated automatically, so this issue can be closed when the `name` attibute description is revised.
