### ISSUE TITLE
Doc design pattern for customizing strings

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/docs#201]
Typically companies want to use the same generated strings across their deliverables. This can be implemented with the following design pattern:

Create a plugin like the following:
```
<plugin id="com.example.strings">
    <require plugin="org.dita.pdf2"/>
    <feature extension="dita.xsl.strings" file="strings/strings.xml"/>
</plugin>
```

The **require** is necessary or the PDF plugin may/will overwrite your strings.

Define your strings. Use the new variable format (see xsl/common/strings.rnc).

Your other plugins _should_ specify your strings plugin as a dependency, and _may_ individually override specific strings themselves where needed.

This lets you set all your strings in a single place rather than using the customization folder structure in your PDF plugins (of course, that's still available).

**Comment by infotexture** [comment]
👍 Sounds like it would make sense to either revise existing topics to mention this, or add a new topic.

_Pull request welcome…_

**Comment by shaneataylor** [comment]
Planning to do this. Also important to note:

**Changes to strings implemented by a plugin affect _all_ output formats using the changed string, not just that plugin.**

For that reason:
- Plugins introducing _new_ strings should as a best practice employ some sort of namespacing.
- You might want to use a strategy of installing a plugin to generate one set of output, and then uninstalling it and installing a different plugin to generate other output when the same strings are defined differently by your plugins.

**Comment by infotexture** [comment]
Looks like this could also cover #165.
