### ISSUE TITLE
Maplink extension point does not exist

### ISSUE THREAD

**Issue by robander** [dita-ot/docs#210]
I tried using this parameter: `dita.preprocess.maplink.param`

Documented here:
http://www.dita-ot.org/dev/extension-points/plugin-extension-points-xslt-parameters.html

Which resulted in a failure, because the extension point does not exist (it's commented out):
```
Error: Plug-in org.oasis.spec.preprocnumbering uses an undefined extension point
 dita.preprocess.maplink.param
```

The other `.param` extension points are marked deprecated in `plugin.xml`, but are still valid.

**Comment by infotexture** [comment]
@robander Good catch, thanks.

That topic is manually authored, so it probably was not removed at some point in the past when preprocessing was refactored.

I'll verify the remaining entries agains the generated list of [All DITA-OT extension points](http://www.dita-ot.org/dev/extension-points/all-extension-points.html).

**Comment by robander** [comment]
Just realized this no longer working was also open as a defect: https://github.com/dita-ot/dita-ot/issues/2697
