### ISSUE TITLE
Add support for user defined properties in DITAVAL

### ISSUE THREAD

**Issue by rahulraykor** [dita-ot/docs#228]
I need to filter out the topics based on "outputclass" property, which is present in my topic.
But even if I add exclude in DITAVAL based on that property, all the topics are appearing in converted document 
I am using following ditaval

```
<?xml version="1.0" encoding="utf-8"?>
<val>
  <otherprop action="exclude" att="outputclass" val="Dx:Landscape" />
  <prop action="exclude" att="product" val="basic" />
</val>
```

I have checked FilterUtil class, there only few properties are mentioned. Is it possible to create that dynamically from user input?

**Comment by robander** [comment]
The DITA specification explicitly states which attributes are allowed for filtering, so DITA-OT only allows filtering based on those. The attributes allowed for filtering are `@audience`, `@platform`, `@product`, `@otherprops`, `@props`, and attributes specialized from `@props`: http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part1-base/langRef/ditaval/ditaval-prop.html

The DITAVAL sample above also uses an `<otherprop>` element, which is not valid -- all filtering instructions in the DITAVAL should use the `<prop>` element.

**Comment by infotexture** [comment]
Closing as unrelated to the DITA Open Toolkit documentation.

For bug reports and feature requests, use the [issue tracker in the dita-ot repository](https://github.com/dita-ot/dita-ot/issues/).

For support questions, please use the community support channels listed in the [SUPPORT file](https://github.com/dita-ot/dita-ot/blob/develop/.github/SUPPORT.md).
