### ISSUE TITLE
Error in "Building output using the dita command"

### ISSUE THREAD

**Issue by keberlein** [dita-ot/docs#23]
In the example section, the path to sequence.ditamap is wrong. It should be ../samples/sequence.ditamap

**Comment by infotexture** [comment]
@keberlein The path `samples/sequence.ditamap` is correct if the command is issued directly from the DITA-OT installation directory, which I assume would be the norm.

This requires that `install-dir/bin` be added to _$PATH_, but we mention that in the preceding topic [Installing the client package](http://www.dita-ot.org/2.1/getting-started/installing-client.html):

> Add the absolute path for the `bin` directory to the `PATH` system variable.
> This defines the necessary environment variable to run the **dita** command from the command-line.

Without the _$PATH_ entry, the command could be run as follows from the _install-dir_

    bin/dita -f html5 -i samples/sequence.ditamap -o test

but I think that's potentially more confusing.

My understanding is that we assume people will create the _$PATH_ entry so the **dita** command is available anywhere. 

Any other opinions?

**Comment by infotexture** [comment]
We do flag the _$PATH_ step with `@importance="optional"`, perhaps we should change that to more explicitly recommend the path entry.

**Comment by robander** [comment]
Probably best to recommend it but maybe still good to show how to do it without. The main reason we ended up with a "full easy install" in the first place - well, specifically, the main reason we ended up with `startcmd.bat` - was that so many people were uncomfortable with editing or unable to edit their path variables.

**Comment by infotexture** [comment]
OK, I'll add a second example _(like above)_ and explain when each applies.
