### ISSUE TITLE
Error in "Building output using Ant" topic

### ISSUE THREAD

**Issue by keberlein** [dita-ot/docs#24]
Refers to the startcmd.bat and startcmd.sh files that are no longer shipped with the DITA-OT.

**Comment by robander** [comment]
They're shipped in the client package (rather than Full Easy Install). I think the plan is/was to remove them from DITA-OT 2.1 but they're still in git as of now.

**Comment by infotexture** [comment]
Still in Git, but excluded from distribution packages since May 9 commit dita-ot/dita-ot@cf98a2b93e113e6f775550a302655335bced46a6.

See [Line 108](https://github.com/dita-ot/dita-ot/blob/cf98a2b93e113e6f775550a302655335bced46a6/build.xml#L108).

**Comment by infotexture** [comment]
@jelovirt In the absence of `startcmd` scripts, how do we recommend users run existing Ant build scripts?

Running `./bin/ant -f build-script target` from the OT installation directory could work, but not sure how reliably w/o the `$ANT_OPTS` & `$ANT_HOME` from `startcmd`.

**Comment by jelovirt** [comment]
`bin/ant` is not there anymore in 2.1, just `dita` and `dita.bat`. My preference is to just tell users that if they want to run Ant directly, then install Ant and set up the classpath in your environment, that our way is the `dita` command. I know people are really attached to their Ant scripts but I want to make DITA-OT distributions smaller and give one way of doing things. The "toolkit" part of DITA-OT will still allow you to run DITA-OT via Ant, but the one way I want to advertise is the command line tool. (The `startcmd.bat` was a workaround, it should not be seen as something to hold on to when there's a better way.)

**Comment by jelovirt** [comment]
Copying `ant.bat` from an older version of DITA-OT to `bin` directory will work, if someone wants the short and ugly fix to use Ant with Ant command line.

**Comment by jelovirt** [comment]
I think we don't currently have a task for how to embed DITA-OT, which is basically the same as running it directly from Ant. So, I do think there should be a page about running DITA-OT via Ant. The instructions are basically that

1.  Install Ant and set `ANT_HOME`

**Comment by infotexture** [comment]
The `startcmd` & bundled Ant binaries were restored in dita-ot/dita-ot@0d8fc30.

Restored references in 2.1 docs.
