### ISSUE TITLE
Add documentation about creating custom plugin extension points

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#240]
If my DITA OT plugin wants to create its own custom extension points which are later extended by other plugins, I'm not sure if there is anything in the documentation discussing this.

**Comment by infotexture** [comment]
How about [Creating a new plug-in extension point](https://www.dita-ot.org/dev/topics/plugin-newextensions.html)?

**Comment by raducoravu** [comment]
Cool, did not see that.
