### ISSUE TITLE
Clarify Lack of FOP Support for PDF Changebars

### ISSUE THREAD

**Issue by StanDoherty** [dita-ot/docs#241]
## Expected Behavior
The DITA-OT documentation for flagging suggests that the OT supports PDF changebar flagging in PDFs. 
Users expect it to work with the default FOP processor. 

## Actual Behavior
If no version of the FOP processor supports changebar flagging and FOP is the default PDF processor for DITA-OT, the documentation should clarify that the OOTB DITA-OT does not support changebar flagging.  

## Possible Solution
Simply qualify the docs to note that FOP does not support changebar flagging. 

## Steps to Reproduce
1. Detach the attached files (below)

[dita-ot-feature-tests.zip](https://github.com/dita-ot/dita-ot/files/2827792/dita-ot-feature-tests.zip)

.
2. Run the following command:
```
c:\dita-ot\bin\dita --input=test_001_pdf-changebars.ditamap --format=pdf --filter=test_001_pdf-changebars.ditaval --output=output\pdf
```
3. Review PDF output.

## Copy of the error message, log file or stack trace
N/A

## Environment
* DITA-OT version: OOTB 3.2.1
* Operating system and version: Windows and MacOS
* How did you run DITA-OT?
  See Steps to Reproduce above
* Transformation type:
   FOP PDF

[dita-ot-feature-tests.zip](https://github.com/dita-ot/dita-ot/files/2827798/dita-ot-feature-tests.zip)

**Comment by infotexture** [comment]
@StanDoherty The [Generating revision bars](http://www.dita-ot.org/dev/topics/pdf2-creating-change-bars.html) topic begins by saying that changebars require either Antenna House or XEP:

> If you use Antenna House Formatter or RenderX XEP, you can generate revision bars in your PDF output by using the `@changebar` attribute of the DITAVAL `<revprop>` element.
> **Note:** FOP […] does not support the XSL `fo:change-bar` formatting object.

I'll update the topic to state the specific FOP version bundled with the latest toolkit and that future FOP versions may include this support per @drmacro's [comment](https://github.com/dita-ot/docs/issues/241#issuecomment-460297231).

@robander [points out](https://github.com/dita-ot/dita-ot/pull/3111#issuecomment-431110715) that other information in the topic is outdated, so I'll sync those changes while I'm at it.
