### ISSUE TITLE
Clarify verbose/debug logging flags

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#244]
Here: https://www.dita-ot.org/dev/topics/build-using-dita-command.html

There is some documentation like:

     --verbose
    -v
        Verbose logging.
    --debug
    -d
        Debug logging.

As a user of the DITA OT, this does not help, I have no idea of the difference between verbose and debug.
For example in my case I want to run everything as if the "ant" process is run with "-verbose". But actually it's the other way around, I need to use "-d" so that it behaves like "ant -verbose".

**Comment by infotexture** [comment]
@raducoravu Good point, those descriptions are straight from the CLI `--help` output and a bit terse.

We can either augment the CLI descriptions with more … _verbose_ explanations in the docs, or add a bit more detail to the CLI help itself — or both.

@jelovirt What are the main differences between the default log output and these 2 options?

**Comment by raducoravu** [comment]
@infotexture  Looks good, thank you.
