### ISSUE TITLE
HTML to DITA conversion is not documented

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#262]
There are end users attempting to include HTML content in DITA maps and to have it part of the PDF:

https://github.com/dita-ot/dita-ot/issues/3337

But here:
https://www.dita-ot.org/dev/topics/alternative-input-formats.html

the fact that if you have a topicref with "format='html'" it gets converted by the lwdita plugin to a DITA topic and the limitations of the conversion are not documented at all.

I also suggested at some point that this automatic conversion between HTML and DITA for all format='html' topicrefs might not be a good idea and maybe a special format attribute value needs to be used for it: https://github.com/jelovirt/org.lwdita/issues/47

**Comment by infotexture** [comment]
The conversion from HTML to DITA should _not_ be automatic. 

To parse an HTML file as HDITA, the `@format` attribute should be set to `hdita` as described in the docs:

```xml
<topicref href="hdita-topic.html" format="hdita"/>
```

If topicrefs with `format=html` are currently being converted to DITA, that sounds like a bug in the LwDITA plug-in per jelovirt/org.lwdita#47.
