### ISSUE TITLE
Add tips on reducing processing time

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#27]
Based on <http://jelovirt.github.io/2013/11/25/reducing-processing-time.html> per @jelovirt's suggestion.

Consider adding as subsection of [Configuring the DITA Open Toolkit](http://www.dita-ot.org/2.0/dev_ref/configuring-the-dita-ot.html).

**Comment by jelovirt** [comment]
Additional tips:

* Use the latest Java version. DITA-OT 2.0 requires Java 7, but IIRC using the latest version Java 8 will be faster.
