### ISSUE TITLE
Added release date to RNs for 3.3.4

### ISSUE THREAD

**Issue by osg** [dita-ot/docs#275]
## Expected Behavior
I would be able to find out when 3.3.4 was released in the release notes.

## Actual Behavior
The release _date_ for 3.3.4 in the release notes is missing.

## Possible Solution
* Add the date by hand.
* If this is set in some config file, find out where that setting is and change it to include the data for the first entry. [I have not looked at the source code, and am speculating here.]

## Steps to Reproduce

1. In the `userguide.pdf`, go to page 249.
2. See the section called `DITA-OT 3.3.4`.

## Environment
Paper and pencil environment. :)

* DITA-OT version: 3.3.4

**Comment by infotexture** [comment]
The docs in the distribution packages are frozen before the release date is necessarily known, so the date is only added for _prior_  maintenance releases.

The date is added to the latest development version of the docs when each release is final. See 3a14747 for 3.3.4 changes, visible at https://www.dita-ot.org/dev/release-notes/index.html#v3.3.4.

These changes are applied to the versioned subfolders (like `3.3`) whenever a new patch is released.

**Comment by osg** [comment]
Ah, ok. I falsely made the assumption that the release notes would be identical irrespective of format, and I did not think to look at the HTML version. What you say makes sense.
