### ISSUE TITLE
Extend Specification Support section

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#28]
Create a new _DITA Specification Support_ section with two children:
* Current [DITA 1.2 Support](http://www.dita-ot.org/2.1/readme/DITA_v1-2-support.html) topic
* New _DITA 1.3 Support_ topic

1.3 Support topic should provide an overview of supported 1.3 features.

Consider including status of planned feature support w/ links to related issues per @raducoravu's [suggestion](https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/37344).

**Comment by jelovirt** [comment]
1.3 implementation status with issues should not be part of shipped documentation. We could use the wiki, but I would prefer to use the issue tracker with labels.

**Comment by infotexture** [comment]
OK, makes sense w/r/t planned features.

Like for v1.2, the 1.3 topic _should_ provide historic info on the 1.3 features introduced in each release/milestone, so users know what works in each version.

For example:
* Release 2.0 includes initial preview support for DITA 1.3, including … per [2.0 RN](http://www.dita-ot.org/2.0/readme/changes/rel2.0.html)
* Release 2.1 adds …

**Comment by infotexture** [comment]
Qualified DITA 1.3 support as preliminary in 4879f3f & added info on additional DITA 1.3 support in 3a5a042.
