### ISSUE TITLE
Automate deploy previews for docs PRs

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#282]
### We have CI builds for the `dev` docs

- [x] All pushes to the `develop` branch of [dita-ot/docs](https://github.com/dita-ot/docs/) are currently deployed to the `master` branch of [dita-ot/website](https://github.com/dita-ot/website/) and visible at [www.dita-ot.org/dev](https://www.dita-ot.org/dev/).

### Netlify provides deploy previews for website PRs

- [x] Deploy previews are automatically built when pull requests are created from other branches of [dita-ot/website](https://github.com/dita-ot/website/), but so far these branches are created _manually_ for pre-release reviews.

### What's missing is deploy previews for docs PRs

- [x] Add Travis scripts (or GitHub Actions) to push the results of docs PRs to new branches in the site repo and generate a deploy preview in the docs PR, so reviewers can view the changes in the rendered output.

    The website repo doesn't need a corresponding PR for each docs repo PR, it's enough that we generate a branch in website repo for each docs repo PR. These temporary preview branches should be deleted after the docs repo PR has been merged or closed.

**Comment by jelovirt** [comment]
The preview action seems to work. Because it's pretty slow, it might become an issue that if the PR author pushes to the PR every few minutes, the previous actions will not have time to run.

Will enable Travis again.

**Comment by infotexture** [comment]
🙏 Thanks @jelovirt, works as intended, closing.

**Comment by infotexture** [comment]
Implemented in #293, with additional testing in #294, #295, #296, #297, and #299
