### ISSUE TITLE
Command line examples do not work on Mac (probably also Linux)

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#289]
Here:
https://www.dita-ot.org/dev/topics/build-using-dita-command.html

there is an example like this:

    dita-ot-dir/bin/dita --input=input-file --format=format [options]

but from what I tested with a DITA OT 3.5 downloaded and unzipped on Mac OSX you actually need to run it like:

      sh dita-ot-dir/bin/dita --input=input-file --format=format [options]

**Comment by raducoravu** [comment]
Wait, the command line does not work only if you are already located in the "bin" folder.
So only something like this:

    dita --install

would need to be written like this:

    ./dita --install

So the instructions are correct.

**Comment by infotexture** [comment]
@raducoravu The `./` notation should not be necessary either if the DITA-OT `bin/` folder is added to `$PATH` as recommended in https://www.dita-ot.org/dev/topics/installing-client.html.

We might want to mention that in the first example as we have in the previous instance at https://www.dita-ot.org/dev/topics/first-build-using-dita-command.html.

**Comment by jelovirt** [comment]
In *NIX systems like Linux or MacOS, if you have a command in `$PATH`, then you can just run it with the command name, like `dita`; Otherwise you have to that the command with a path, e.g. `./dita`, `bin/dita` or `/abs/path/dita`.

**Comment by raducoravu** [comment]
I understand now.
