### ISSUE TITLE
Add info on converting Markdown to DITA

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#292]
[Question from the DITA-OT Users list](https://groups.google.com/d/msgid/dita-ot-users/201f3390-6bf8-4b02-8583-6304f2da270bo%40googlegroups.com):

> Although I could find information about markdown support in the DITA OT documentation, it is still not clear to me what exactly is supported with regards to markdown.
>
> We'd like to be able to convert markdown files to DITA and wonder if we can use the DITA OT for this purpose.

- Add info to topics on Markdown & LwDITA input to clarify that Normalized DITA output can be used to convert Markdown to DITA
- Add this application scenario to Normalized DITA topic

**Comment by Schelmenzunft** [comment]
Hi Roger,

there was a markdown webinar by Oxygen on Wednesday, and they referred to a github page from Jarno.

https://github.com/jelovirt/dita-ot-markdown/wiki/Syntax-reference

Perhaps a good start to see what’s supported when going from MD to DITA …

Cheers,
Franz-Josef






AKG Software Consulting GmbH
Franz-Josef Knelangen


Uhlandstraße 12
79423 Heitersheim
Germany

Tel.: +49 (0)7634 5612-611
Fax: +49 (0)7634 5612-300
E-Mail: fjk@akgsoftware.de
Internet: www.akgsoftware.de<http://www.akgsoftware.de>

Geschäftsführer: Dipl.-Ing. Artur K. Günther, Dipl.-Ing. Arno Brüggemann, Dipl.-Ing. (FH) Bernhard Feser, Dipl.-Ing. Jens Günther
Sitz der Gesellschaft: Heitersheim, HRB 310383 (Amtsgericht Freiburg)

Von: Roger Sheen <notifications@github.com>
Gesendet: Freitag, 19. Juni 2020 13:30
An: dita-ot/docs <docs@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [dita-ot/docs] Add info on converting Markdown to DITA (#292)



Externe E-Mail: Vorsicht beim Öffnen von Anhängen und Klicken auf Links!


Question from the DITA-OT Users list<https://groups.google.com/d/msgid/dita-ot-users/201f3390-6bf8-4b02-8583-6304f2da270bo%40googlegroups.com>:

Although I could find information about markdown support in the DITA OT documentation,
it is still not clear to me what exactly is supported with regards to markdown.

We'd like to be able to convert markdown files to DITA and wonder if we can use the DITA OT for this purpose.

 *   Add info to topics on Markdown & LwDITA input to clarify that Normalized DITA output can be used to convert Markdown to DITA
 *   Add this application scenario to Normalized DITA topic

**Comment by infotexture** [comment]
@Schelmenzunft Yes, that wiki page was imported to the DITA-OT docs for the 3.0 release back in 2017 with #150.

The result is available at https://www.dita-ot.org/dev/topics/markdown-dita-syntax-reference.html as mentioned in the original post, with the added benefit of syntax highlighting in the code blocks.

/cc @AlexJitianu, @raducoravu

**Comment by Schelmenzunft** [comment]
Very good. Bookmarked. A little typo in the list section: ampersand should be replaced with asterisk.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>




AKG Software Consulting GmbH
Franz-Josef Knelangen


Uhlandstraße 12
79423 Heitersheim
Germany

Tel.: +49 (0)7634 5612-611
Fax: +49 (0)7634 5612-300
E-Mail: fjk@akgsoftware.de
Internet: www.akgsoftware.de<http://www.akgsoftware.de>

Geschäftsführer: Dipl.-Ing. Artur K. Günther, Dipl.-Ing. Arno Brüggemann, Dipl.-Ing. (FH) Bernhard Feser, Dipl.-Ing. Jens Günther
Sitz der Gesellschaft: Heitersheim, HRB 310383 (Amtsgericht Freiburg)


________________________________
Von: Roger Sheen <notifications@github.com>
Gesendet: Friday, June 19, 2020 11:59:33 PM
An: dita-ot/docs <docs@noreply.github.com>
Cc: Franz-Josef Knelangen <fjk@akgsoftware.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dita-ot/docs] Add info on converting Markdown to DITA (#292)



Externe E-Mail: Vorsicht beim Öffnen von Anhängen und Klicken auf Links!



@Schelmenzunft<https://github.com/Schelmenzunft> Yes, that wiki page was imported to the DITA-OT docs for the 3.0 release back in 2017 with #150<https://github.com/dita-ot/docs/issues/150>.

The result is available at https://www.dita-ot.org/dev/topics/markdown-dita-syntax-reference.html as mentioned in the original post, with the added benefit of syntax highlighting in the code blocks.

/cc @AlexJitianu<https://github.com/AlexJitianu>, @raducoravu<https://github.com/raducoravu>

**Comment by infotexture** [comment]
Good catch. Fixed in https://github.com/dita-ot/docs/commit/7ce65c40e2048dac296ae3ae18069300c99acf20.

**Comment by raducoravu** [comment]
@infotexture thanks for the cc, I will update in the Oxygen user's manual the link to point to the DITA OT docs.
