### ISSUE TITLE
Topic about how to contribute a new language to the DITA OT

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#31]
There seems to be a topic on globalizing the DITA OT:

http://www.dita-ot.org/2.0/readme/DITA-globalization.html

But it does not seem to say anything about how to contribute new translations as a plugin for example.

We probably need to have separate explanations for the PDF processing and for the other transformations.

Based on this question on the DITA Users List:

https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/37719

```
    I am currently adding a few languages to my documentation set. 
     Some of these languages are not supported by my DITAOT. 
      Does anyone know if there are resources that can allow me to add more languages?
```

**Comment by raducoravu** [comment]
A, found something:

http://www.dita-ot.org/2.0/dev_ref/plugin-addgeneratedtext.html

but it does not say anything about PDF.

**Comment by raducoravu** [comment]
I hate it that I do not have a search field in the generated documentation, I always need to expand the TOC in all places and sometimes the TOC keeps collapsing.

**Comment by infotexture** [comment]
I added a reltable link to the topic on generated text as a quick fix, but agree that a dedicated topic would be a good idea.

**Comment by infotexture** [comment]
A site search field on www.dita-ot.org is planned, see dita-ot/dita-ot.github.io#6 for details.
