### ISSUE TITLE
Parameter pdf2.index.skip name wrong?

### ISSUE THREAD

**Issue by Herbert-SDL** [dita-ot/docs#316]
On the page describing the DITA-OT PDF parameters (https://www.dita-ot.org/3.5/parameters/parameters-pdf.html), the parameter to skip index processing is listed as "pdf2.index.skip" (https://www.dita-ot.org/3.5/parameters/parameters-pdf.html#pdf__pdf2.index.skip), but that does not seem to do anything. The parameter that will skip index processing is "org.dita.index.skip"

**Comment by infotexture** [comment]
@Herbert-SDL Thanks for reporting this — however the `pdf2.index.skip` name is _not_ wrong — these 2 parameters are related. 

### Background
  
Up until DITA-OT 3.4, indexing code lived in the PDF plug-in and was not available to other transformations. In version 3.4 and above, indexing is provided by a separate plug-in to allow other transformations to access the results.

For backwards compatibility purposes, these 2 parameters can be used to restore index processing to the PDF plug-in in cases where custom plug-ins expect to extend it there.

Per https://www.dita-ot.org/3.5/topics/migrating-to-3.4.html:
> ### New indexing plug-in
> DITA-OT 3.4 extracts the PDF indexing code to a separate `org.dita.index` plug-in, and adds a new `depend.org.dita.pdf2.index` extension point that can be used to add custom index processing targets to PDF output.
> 
> The built-in index processing has been disabled and deprecated. If you have overridden index processing via the `transform.topic2fo` target in the past, you can set the new `org.dita.index.skip` property to `yes` and re-enable the `transform.topic2fo.index` target with `<feature extension="depend.org.dita.pdf2.index" value="transform.topic2fo.index"/>` in your plug-in configuration.

We should probably improve the description there ☝️ to clarify the relationship between these 2 parameters, and push additional information to the parameter listings in the process.

⚠️ The `org.dita.index.skip` parameter is not currently listed with the other parameters. _(We'll fix that while we're at it.)_

**Comment by Herbert-SDL** [comment]
Hi Infotexture,

Thanks for explaining; this makes sense. I'm implementing an alternative index sorting routine so needed to switch off the index plugin. That only works by setting org.dita.index.skip=yes, so it would indeed be good to have this parameter listed with the other parameters. Thanks!

**Comment by infotexture** [comment]
@Herbert-SDL The [org.dita.index.skip](https://www.dita-ot.org/dev/parameters/parameters-pdf.html#pdf__org.dita.index.skip) parameter is now listed along with the other PDF parameters, and the obsolete `pdf2.index.skip` entry has been removed.

Thanks for bringing this to our attention.
