### ISSUE TITLE
Clarify the speeding up builds topic

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#318]
https://www.dita-ot.org/dev/topics/reducing-processing-time.html

About this section "Use the latest Java version", on Mac OS I obtain no difference in run times using Java 1.8 or Java 15 Open JDK. On Windows on the contrary Java 15 may add about 30% more time, they seem to have some kind of bug which makes file access slower, I added an issue on the Java issues list but it has not yet been accepted. So right now on Windows using Java 1.8 is fastest and on Mac it does not matter either way.
I'm testing publishing the Oxygen user guide to HTML5 with a filter "editor-sa.ditaval":
https://github.com/oxygenxml/userguide-private

About the section "Reuse the JVM instance" how would one go around testing this? Maybe give some steps there. I'm skeptical, it says "the performance increase may be 2-10 fold". So if on Mac the publishing process takes about 2 minutes, does this mean that it would end in one minute?

**Comment by infotexture** [comment]
@raducoravu Thanks for pointing this out. 

(We'll also need to update this with info on the new features in 3.6 for in-memory and parallel processing.)

**Comment by raducoravu** [comment]
@infotexture right, on Windows the in-memory storage almost reduces in half the publishing time, so it's a big difference. The parallel processing reduces the publishing time but not by that much.

**Comment by jelovirt** [comment]
Documenting how to reuse a JVM is out of scope for our docs. You'd do it by e.g. running a JVM as a daemon and triggering DITA-OT processing with e.g. a HTTPS end-point or a watch folder. We could use the Gradle DITA-OT plug-in as an exmple of this?

The performance boost you will get from reusing the JVM is most visible with small input sets. The larger the input set is, the smaller the difference.

**Comment by infotexture** [comment]
@jelovirt Thanks, makes sense to link to [eerohele/dita-ot-gradle](https://github.com/eerohele/dita-ot-gradle) as example. 👍

**Comment by raducoravu** [comment]
@jelovirt about DITA OT with Java 15 running slower on Windows with a large DITA project, just to note I added a bug on the Java bugs list about this: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8258196
I tried to reproduce in the bug this behavior of the DITA OT which reads and writes files in each stage.

**Comment by raducoravu** [comment]
Adding here also some timings when re-using the same Java VM to run the publishing.
For publishing the Oxygen XML Blog (https://github.com/oxygenxml/blog) to WebHelp Responsive using DITA OT 3.6 (without store-type and parallel processing) on Mac OS the first processing takes 16 seconds in the Java VM and the second processing takes 8 seconds. The Java code I'm using is something like:

      public static void main(String[] args) throws DITAOTException {
		if (args != null && args.length == 0) {
			args = new String[1]; args[0] = "webhelp-responsive";
		}
		String ditaHome = "/Users/raducoravu/Downloads/dita-ot-3.6";
		ditaDir = new File(ditaHome).getAbsoluteFile();
		tempDir = new File("temp").getAbsoluteFile();
		mapFile = new File("/Users/raducoravu/Downloads/blog-master/oxygen_xml_blog.ditamap").getAbsoluteFile();
		outDir = new File("out");
		outDir = new File(outDir, args[0]).getAbsoluteFile();
		ProcessorFactory processorFactory = ProcessorFactory.newInstance(ditaDir);
		// and set the temporary directory
		processorFactory.setBaseTempDir(tempDir);
		
		// Create a processor using the factory and configure the processor
		Processor processor = processorFactory.newProcessor(args[0])
		.setInput(mapFile)
		.setOutputDir(outDir);

		processor.createDebugLog(false);
		processor.cleanOnFailure(true);
		
		for (int i = 0; i < 3; i++) {
			System.err.println("Run iteration " + i);
			long before = System.currentTimeMillis();
			// Run conversion
			processor.run();
			long after = System.currentTimeMillis();
			System.err.println("Took " + (after - before));
		}
	}

I think this improvement in speed comes from the caching Saxon does of document() XSLT function invocations. And also by avoiding to re-parse the DITA DTDs as the GrammarPoolManager is already filled.

For the Oxygen User guide (about 2000 topics) a similar code yields about 177 seconds in the first iteration and 143 seconds in the second iteration.

**Comment by jelovirt** [comment]
To run the same conversion multiple times, you don't need your own main method anymore. I added ` --repeat=N` option to the CLI in 3.6.

**Comment by jelovirt** [comment]
>I think this improvement in speed comes from the caching Saxon does of document() XSLT function invocations.

AFAICT, this is not the case because Saxon doesn't store these into any global store in memory. They're bound to `XsltTransformer` and we don't reuse those between transtype processes.

**Comment by raducoravu** [comment]
@jelovirt the document pool is a local field in the Transformer configuration "net.sf.saxon.Configuration.globalDocumentPool". And the "Configuration" is created on the "org.dita.dost.util.XMLUtils.XMLUtils()" constructor. Meaning that for each single XMLUtils instance the cache is preserved. The XMLUtils instance is preserved as a key "org.dita.dost.util.Constants.ANT_REFERENCE_XML_UTILS" in the Project instance. And each call to "org.dita.dost.Processor.run()" creates another Project instance. So indeed I think you are right, as a new Project is created by the Processor every time this would mean a new XMLUtils instance with a new configuration is used. And the new configuration has a different global document pool.

**Comment by jelovirt** [comment]
Even within the same Project, IMO the `globalDocumentPool` is not used to cache the `document()` call results for separate `XsltTransformer` instances. If they were, we would not be able to get the current state of the temporary files during preprocessing, except when the first XSLT in preprocessing is run.
