### ISSUE TITLE
Document PDF2 interpretation of the DITAVAL @changebar attribute

### ISSUE THREAD

**Issue by drmacro** [dita-ot/docs#32]
The PDF2 transform handles a special syntax for the `@changebar` attribute in order to generate revision bars with FO when it is supported (AHF, XEP). This appears to be undocumented. I will document it.

**Comment by keberlein** [comment]
Before you expend energy on this, let me see if I have already
    effectively done this for a client. 
    
    Best,
      Kris
      
      Kristen James Eberlein
      Chair, OASIS DITA Technical Committee
      Principal consultant, Eberlein Consulting
      www.eberleinconsulting.com
      +1 919 682-2290; kriseberlein (skype)
      
    
    On 7/27/2015 11:52 AM, Eliot Kimber
      wrote:
    
    
      The PDF2 transform handles a special syntax for the @changebar
        attribute in order to generate revision bars with FO when it is
        supported (AHF, XEP). This appears to be undocumented. I will
        document it.
      —
        Reply to this email directly or view it on
          GitHub.

**Comment by drmacro** [comment]
Too late, I already wrote the topic.
Cheers,
E. Eliot Kimber
Austin, TX 


     On Monday, July 27, 2015 10:59 AM, Kristen James Eberlein <notifications@github.com> wrote:
   

 
 
 
 
 
 Before you expend energy on this, let me see if I have already
 effectively done this for a client. 
 
 Best,
 Kris
 
 Kristen James Eberlein
 Chair, OASIS DITA Technical Committee
 Principal consultant, Eberlein Consulting
 www.eberleinconsulting.com
 +1 919 682-2290; kriseberlein (skype)
 
 
 On 7/27/2015 11:52 AM, Eliot Kimber
 wrote:
 
 
 The PDF2 transform handles a special syntax for the @changebar
 attribute in order to generate revision bars with FO when it is
 supported (AHF, XEP). This appears to be undocumented. I will
 document it.
 —
 Reply to this email directly or view it on
 GitHub.—

**Comment by infotexture** [comment]
@keberlein If you have anything you can share & post a [gist](https://gist.github.com), I'd be happy to see how it fits with the topic @drmacro submitted in #33.

**Comment by infotexture** [comment]
Fixed with #33.
