### ISSUE TITLE
Inclusive terminology in docs and DITA OT files

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#328]
For example in "plugins/org.dita.base/plugin.xml" there is a "master file" which can be probably replaced with "main file".

**Comment by keberlein** [comment]
FWIW, for the spec, we are replacing references to "master map" with "root map." Obviously that is not congruent with what we are talking about here, but it would be nice if spec and DITA-OT docs used the same terminology to refer to the map that is input to the processor.

**Comment by infotexture** [comment]
In earlier discussions, we agreed "root map" should be used consistently, so we'll align to that and use "main file" in the `args.input` description to account for cases where single topics are transformed.
