### ISSUE TITLE
Explain if it is possible (or not) and how to use an extension point several times

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#341]
## Description
It seems that it is not possible to use an extension point more than one time. For example, if you use the customized oXygen XML DITA-OT, the `com.oxygenxml.pdf.custom` plugin blocks the `depend.org.dita.pdf2.init.pre` extension point, therefore I cannot use it with "my" plugin and need to uninstall the `com.oxygenxml.pdf.custom` plugin (because no other extension point works for me).

## Possible Solution
If it is not possible to use an extension point twice, it could be a good idea to make a note in the docs, that this is not possible. If it is possible, it would be good to have a very small code snippet that explains how this can be implemented.

**Comment by jelovirt** [comment]
@xephon2, that's weird. I would have said the and dependency extension points can be declared multiple times.

What does `com.oxygenxml.pdf.custom` actually do if it blocks `depend.org.dita.pdf2.init.pre`?

**Comment by xephon2** [comment]
I've retested this. It seems to work, must have been a mistake on my end.
