### ISSUE TITLE
Update Implementation dependent features for DITA 1.3

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#36]
On Wednesday, 2015-09-02, at 16:30 CEST, @jelovirt wrote:

> We will probably need to update http://www.dita-ot.org/dev/dev_ref/DITA1.2-implementation-dependent-features.html to fill in how we implement DITA 1.3 
> 
> Basically, we’d need to go though the 1.3 spec and find all places that state that an implementation MAY do X. Then just list what we do.

**Comment by infotexture** [comment]
We should also consider moving this topic from the _Developer Guide_ to the _DITA specification support_ section of the _User Guide_ (alongside the _DITA 1.3 support_ topic).

**Comment by EditKoselak** [comment]
Hi @infotexture, @jelovirt, is this issue still relevant? If yes, I'd be happy to work on it.
