### ISSUE TITLE
Add args.xhtml.toc.xsl to "Ant parameters: Common HTML-based transformations"

### ISSUE THREAD

**Issue by markgif** [dita-ot/docs#39]
The Ant parameter args.xhtml.toc.xsl is missing from the docs. It specifies a custom XSLT file to use for the TOC (index.html).

**Comment by jelovirt** [comment]
@infotexture, how about a copy:

```xml
<param name="args.xhtml.toc.xsl" desc="Specifies a custom XSL file to be used for TOC generation." type="file"/>
```

**Comment by infotexture** [comment]
The proposed description looks fine.

Just needs to be added to `org.dita.xhtml/plugin.xml` alongside the `args.xhtml.toc` & `args.xhtml.toc.class` parameter descriptions for inclusion in the autogenerated docs topics.

Those are specific to the HTML5 and XHTML transformations, so they appear under [Ant parameters: HTML](http://www.dita-ot.org/dev/parameters/ant-parameters-html5-transformation.html).

**Comment by jelovirt** [comment]
Added to HTML plugin.xml configuration.

**Comment by infotexture** [comment]
The parameter description is now included in the _Development_ docs under [Ant parameters: HTML](http://www.dita-ot.org/dev/parameters/ant-parameters-html5-transformation.html).

**Comment by markgif** [comment]
Thanks!
