### ISSUE TITLE
Push `--resource` details to `args.resources` description

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#391]
The autogenerated listing for the [args.resources](https://www.dita-ot.org/dev/parameters/parameters-base.html#base__args.resources) parameter should be extended with additional details from the [--resource](https://www.dita-ot.org/dev/topics/build-using-dita-command.html#--resource=file) CLI parameter description and the [3.5 Release Notes](https://www.dita-ot.org/3.5/release-notes/#v3.5__features).

The current listing includes only the info from plug-in source, whereas other parameter descriptions are augmented with additional content via the conref-push mechanism.

- [x] Push details to `args.resources` description
- [x] Add reciprocal links between CLI options & corresponding parameter listings

**Comment by jelovirt** [comment]
Should we try to extend the property list generation XSLT so that it automatically links to CLI arguments? Or is it enough that we maintain these by hand?
