### ISSUE TITLE
Message about rewritten duplicate ID not documented

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#396]
We had this report from one of our users:

> I am receiving a transformation problem I do not know how to resolve:
>
> [DOTX077I]: Resolving content references results in duplicate ID 'table_qpb_sby_ysb'.
> Rewriting resolved version to 'd107e359'
>
> The Message ID "DOTX77077I" does not appear on the DITA-OT error messages page
> located here: https://www.dita-ot.org/dev/topics/error-messages.html

Indeed this particular message does not seem to be documented.

**Comment by infotexture** [comment]
@raducoravu The [error messages](https://www.dita-ot.org/dev/topics/error-messages.html) topic is generated from code, so we'll need to investigate with @jelovirt why this particular message is not included in the table.

Once we figure that out, we can look into adding additional details.

**Comment by jelovirt** [comment]
Message [`DOTX077I`](https://www.dita-ot.org/dev/topics/error-messages.html#msgs__DOTX077I) is documented, but not `DOTX77077I`.

**Comment by raducoravu** [comment]
@jelovirt I will close this one, it's possible that when I added the issue the "DOTX077I" was somehow not present in that errors table from the published docs.
