### ISSUE TITLE
Explain DITA-OT message parameters

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#403]
## Description
The topic [plugin-messages](https://www.dita-ot.org/dev/topics/plugin-messages.html) should explain how to pass parameters to messages. Messages are computed by [`output-message.xsl`](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.base/xsl/common/output-message.xsl#L22). The supported parameters are:

* `ctx`
* `id`
* `msg`
* `msgparams`

> The parameter `msgparams` is not explained.

For example to call `DOTX001W` and set the parameters `%1`, `%2`, and `%3`,you need to do something like this:

```xml
<xsl:call-template name="output-message">
  <xsl:with-param name="id" select="'DOTX001W'"/>
  <xsl:with-param name="msgparams">%1=<xsl:value-of select="$stringName"/>;%2=<xsl:value-of select="$ancestorlang"/>;%3=<xsl:value-of select="$DEFAULTLANG"/></xsl:with-param>
</xsl:call-template>
```

**UPDATE**

Further on, please also add a note that you unfortunately cannot change the severity when overriding the message.

![image](https://user-images.githubusercontent.com/3266567/164247994-d9ade33e-bbaf-442a-8950-611efb87bdb2.png)

**Comment by jelovirt** [comment]
The value of `msgparams` is a semicolon separated list of strings, where each token consists of a percent sign prefixed parameter index, equals sign and parameter value.

The reason why the parameter is not typed as `xs:string*` is for backwards compatibility.

**Comment by xephon2** [comment]
@infotexture, could you please tell me if you agree that this should be added to the docs? I could send a PR.

**Comment by infotexture** [comment]
@xephon2 Sure, if you have ideas on how to improve these topics, contributions are welcome.

**Comment by infotexture** [comment]
@xephon2 Anything else needed here, or can we close this now that #405 has been merged?

**Comment by xephon2** [comment]
@infotexture Issue can be closed.
