### ISSUE TITLE
Clarify some aspects for including javascript in header/footer

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#409]
I was helping someone following this topic and who created a plugin based on it:
https://www.dita-ot.org/dev/topics/html-customization-plugin-javascript.html#ariaid-title1
They made two mistakes:
1) In the build.xml they made the reference to the footer file something like this:

       <property name="args.ftr"
          location="${mypluginID}/include/javascript.ftr.xml"/>

so they did not prefix and suffix it as **${dita.plugin.mypluginID.dir}** , maybe the documentation should state this more clearly.

2) Their "javascript.ftr.xml" XML file containing the footer was not wellformed. It had an attribute which did not have a value:

        <div>
        <script>
            <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
        </script>
        </div>

so maybe again state in the documentation that the XML file needs to be wellformed, maybe give also this example about an attribute without value which needs to be converted to:

        <div>
        <script>
            <script id="MathJax-script" async="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
        </script>
        </div>

**Comment by infotexture** [comment]
@raducoravu Thanks for your suggestions. 

1. The example in the topic _already_ shows the use of the plug-in directory property:

   ```xml
   <property name="args.ftr"
             location="${dita.plugin.com.example.html5-javascript.dir}/include/javascript.ftr.xml"/>
   ```
   but I've added a note to call attention to this detail:
   > **Note:** When defining the path to the footer file from the Ant script, use the plug-in directory property with the plugin-id as shown in the example above: `${dita.plugin.plugin-id.dir}`.
2. The need for valid XML is mentioned in the [args.ftr parameter description](https://www.dita-ot.org/dev/parameters/parameters-base-html.html#base-html__args.ftr), but I've repeated that here to make it more discoverable, and added the `async` script attribute example.
