### ISSUE TITLE
Wrong element name in plugin.xml

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#419]
The [Plug-in descriptor file](https://www.dita-ot.org/dev/topics/plugin-configfile.html#meta) mentions an element called **`<meta>`**, but the correct element name is **`<metadata>`**, see [plugin.rnc](https://github.com/dita-ot/dita-ot/blob/15ffea9422f0c97ed656a9e4e5e4b267185e1ea7/src/main/resources/plugin.rnc#L67). A **`<meta>`** element does not exist.

**Comment by infotexture** [comment]
🙏 Thanks Stefan, good catch. 

✅  [Fixed](https://www.dita-ot.org/dev/topics/plugin-configfile.html#metadata).
