### ISSUE TITLE
plugin.xml <transtype> element not documented

### ISSUE THREAD

**Issue by markgif** [dita-ot/docs#42]
It looks like the <transtype> element in plugin.xml is not documented on this page:

https://github.com/dita-ot/docs/blob/develop/dev_ref/plugin-configfile.dita

An example of this element is here:

https://github.com/oxygenxml/dita-css/blob/master/com.oxygenxml.pdf.css/plugin.xml

Thanks,
Mark

**Comment by infotexture** [comment]
@markgif Were you looking at an older version of the topic?

The description of the new `<transtype>` element was added for #40 and appears on [Lines 129–198](https://github.com/dita-ot/docs/blob/develop/dev_ref/plugin-configfile.dita#L129-L198).

See http://www.dita-ot.org/dev/dev_ref/plugin-configfile.html for a rendered version of the latest 2.2 draft.

**Comment by markgif** [comment]
Oh it is documented, thanks. I'm using OT 1.8 in what I'm doing, with <transtype> in the plugin.xml file, and it works. Maybe 1.8 doesn't use <transtype> and it's set up to be backwards compatible?

Anyway I looked at the 1.8 docs for this, and the 2.0 docs. Guess I should have gone all the way to the newest!

http://www.dita-ot.org/1.8/dev_ref/plugin-configfile.html
http://www.dita-ot.org/2.0/dev_ref/plugin-configfile.html

Mark
