### ISSUE TITLE
Document the "filter-attributes" parameter from the DITA-OT/config/configuration.properties file

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#420]
This parameter allows you to add extra filter attributes to be taken into account by the DITA OT.
The feature seems to have been added here: https://github.com/dita-ot/dita-ot/pull/2784

**Comment by jelovirt** [comment]
https://github.com/dita-ot/dita-ot/blob/develop/src/test/resources/TestDitaValReader/src/any.ditaval is an example of file that uses custom attributes.

**Comment by raducoravu** [comment]
Thanks @infotexture
