### ISSUE TITLE
Section "Customizing PDF output" does not explain how to customize the PDF style/layout

### ISSUE THREAD

**Issue by philipaxer** [dita-ot/docs#428]
## Description
As of today, the section "customizing PDF output" explains approaches to change the pdf flow through the means of custom plug-ins & customization directories. However as an end-user i would expect that this section also tells me *how* to change the actual PDF layout/look-and-feel in detail. I personally dont have a deep understanding of what dita-ot does under the hood, but would still like to change the style of the pdf.

## Possible Solution
Ideally the process of creating/modifying the style of the generatdd PDF is described and some examples are given.  If this is falling out of the scope of this project, at least links to the relevant external resources should be given.

**Comment by infotexture** [comment]
@philipaxer 🙏 Thanks for your feedback.

The full range of customization options is indeed a bit beyond the scope of this project, as several [Books](https://www.dita-ot.org/dev/reference/books.html) have been written about the subject.

That said, we're working on a simpler way to adjust basic styling via theme files, and will include examples in the documentation once that feature ships.

_Stay tuned…_

**Comment by infotexture** [comment]
PDF themes shipped in DITA-OT 4.0, and a new docs section now describes basic customizations.

For details, see [PDF themes](https://www.dita-ot.org/dev/topics/pdf-themes.html).
