### ISSUE TITLE
Create Gradle build file for docs

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#44]
Now that the main DITA-OT repo uses Gradle to build, we should prepare a `build.gradle` file for `docs`  to employ the [DITA Open Toolkit Gradle Plugin](http://eerohele.github.io/dita-ot-gradle/build/) for better performance, incremental builds and continuous builds via the Gradle Daemon.

This solution would facilitate local testing by rebuilding docs whenever source files change, and could also serve as a foundation for continuous integration of changes to **Development** docs on the project website at www.dita-ot.org/dev per dita-ot/dita-ot.github.io#9.

**NOTE:** To prevent code duplication and still allow users that don't have Gradle to build the docs, it might be best if the `build.gradle` file could call the existing [Ant build file](https://github.com/dita-ot/docs/blob/develop/build.xml), or re-use the targets it defines.

**Comment by eerohele** [comment]
If you just want to use the targets in the existing Ant build file, you don't need the DITA-OT Gradle Plugin. You can just create a `build.gradle` file that looks like this:

```groovy
task pdf << {
    ant.ant(antfile: 'build.xml', target: 'pdf')
}

task html << {
    ant.ant(antfile: 'build.xml', target: 'html')
}

task htmlhelp << {
    ant.ant(antfile: 'build.xml', target: 'htmlhelp')
}

task clean << {
    ant.ant(antfile: 'build.xml', target: 'clean')
}

task all(dependsOn: ['pdf', 'html', 'htmlhelp'])

defaultTasks 'all'
```

That's enough to get the performance benefit, as well as the incremental and continuous builds. You'll still be able to use the Ant buildfile just like before, too.

**Comment by eerohele** [comment]
Oh, wait, sorry, you'll only the performance benefit that way, of course.

To get the other things, you'll need to declare the inputs and outputs of each task explicitly, or use the DITA-OT Gradle Plugin, but I don't think you can reuse the current Ant tasks in that case.

**Comment by infotexture** [comment]
Re-using targets from the Ant `build.xml` file in `build.gradle` looks like a good compromise that would allow us to use Gradle for the docs build process when building DITA-OT packages, yet still allow others to build docs with Ant without requiring Gradle.

The `site.xml` build could be refactored in Gradle to take full advantage of the DITA-OT Gradle Plugin, since that process should only be run by collaborators who have Gradle anyway.

**Comment by eerohele** [comment]
Since `site.xml` uses targets from `build.xml` that automatically generate some of the topics, it's difficult to avoid *any* code duplication *and* make use of all of Gradle's nice features.

Here's a Gradle buildfile you can try out:

```groovy
plugins {
    id 'com.github.eerohele.dita-ot-gradle' version '0.1.0'
}

import com.github.eerohele.DitaOtTask

defaultTasks 'site'

// Use the DITA-OT dir defined by the dita.home system property. If undefined,
// use the parent directory.
def ditaHome = System.getProperty('dita.home', '../')

// Point DITA-OT Gradle Plugin to the DITA-OT directory.
ditaOt.dir ditaHome

task messages {
  inputs.file "${ditaHome}/resources/messages.xml"
  outputs.file "${projectDir}/user-guide/DITA-messages.xml"

  doLast {
    ant.ant(antfile: 'build.xml') {
      target name: 'generate-msg-topic'
    }
  }
}

task params {
  inputs.file "${ditaHome}/resources/plugins.xml"
  outputs.dir "${projectDir}/parameters"

  doLast {
    ant.ant(antfile: 'build.xml') {
      target name: 'generate-params-topic'
    }
  }
}

task extensionPoints {
  inputs.file "${ditaHome}/resources/plugins.xml"
  outputs.dir "${projectDir}/extension-points"

  doLast {
    ant.ant(antfile: 'build.xml') {
      target name: 'generate-extension-points-topic'
    }
  }
}

task generateTopics(dependsOn: ['messages', 'params', 'extensionPoints'])

task site(type: DitaOtTask, dependsOn: 'generateTopics') {
    input 'site.ditamap'
    output file('../lib/dost.jar').exists() ? '../docs' : 'out'

    transtype 'org.dita-ot.html'

    properties {
        property name: 'args.gen.task.lbl', value: 'yes'
        property name: 'args.rellinks', value: 'noparent'
    }
}
```

It will only generate the message, parameter, and extension point topics if the source files for those topics have changed. If that feature is not necessary, we can simplify the script a bit. Just let me know what you prefer.

If we do want to have that feature, though, it would be better if the DITA source files were reorganized so that there are no directories that contain both manually maintained and automatically generated files. Currently, the `parameters` directory contains both.

I can also submit the script as a PR and we can iterate that way if you prefer.
