### ISSUE TITLE
Improve Markdown docs for those evaluating LwDITA

### ISSUE THREAD

**Issue by darrenn-jackson** [dita-ot/docs#475]
## Description

Improve the docs covering Markdown and MDITA processing to help individuals and orgs who are evaluating LwDITA. Reduce confusion and explain things that aren't immediately obvious.

## Possible Solution

1. "Markdown content" under "Authoring formats" needs to be more clear that there are two Markdown-to-DITA mappings and that this topic is not about MDITA.
2. Explain that if you're evaluating or using LwDITA, you should:

   1. Uninstall the `org.oasis.xdita` plugin already installed with DITA-OT.
   2. Zip up the `org.oasis.xdita` subdirectory of the LwDITA repo yourself. 
   3. Install the zip file of the plugin you just made. 
   4. Refer to the nightly build of the [draft spec](https://dita-lang.org/lwdita/introduction/introduction.html). 
  
   Neither the draft grammar files, nor the draft spec will 100% match the final, offical LwDITA spec and grammar files, but they'll be far closer than the Committee Note and grammar files from 2018. Otherwise, you'll get the impression that LwDITA's syntax is more limited that it actually is, and that's unfair to LwDITA.
6. Add a pros/cons table comparing "Markdown DITA" to MDITA.
7. Explain that the syntax for for inserting a conref from one MDITA topic into another MDITA topic is: `<p conref="CONREF_TARGET_PATH/CONREF_TARGET_FILE_NAME#CONREF_TARGET_TOPIC_ID/CONREF_TARGET_CONTENT_ID" />` and point out:

   -  You have to include both the MDITA conref target file name **and** the topic-level id. You'd think that either one would suffice, but that's not how it works.
   - In contrast to Markdown xrefs, you don't use the Markdown level 1 or level 2 header that contains the conref target content anywhere in that link. After the file name & path, it's all ids.

## Additional Context

I'm currently testing and evaluation LwDITA for possible adoption by my organization. These items tripped me up and will most likely impact others.

**Comment by infotexture** [comment]
@fwegmann, @keberlein In the [May contributors call](https://github.com/dita-ot/dita-ot/wiki/Meeting-minutes-2023-05-04), we talked about the possibility of bundling a newer version of the XDITA draft grammar files in the upcoming 4.1 release of DITA-OT.

So far, the [latest tag](https://github.com/oasis-tcs/dita-lwdita/tags) on the [oasis-tcs/dita-lwdita](https://github.com/oasis-tcs/dita-lwdita/) repo is still 0.2.2 from October of 2018. 

Any chance you could tag a more recent snapshot that we could bundle in DITA-OT 4.1 to address № 2 above?

**Comment by infotexture** [comment]
Also @fwegmann & @keberlein: Is there an “official” LwDITA syntax for MDITA con(key)refs, or is the XDITA-in-MDITA workaround outlined in № 4 above the only option?

**Comment by infotexture** [comment]
Docs are updated for 4.1, which also includes the latest version of the XDITA grammar files.
