### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by CsatariGergely** [dita-ot/docs#479]
## Expected Behavior
Build suceeds after executing the commands in the README file

## Actual Behavior
I get an error message: 

> Task :generatePropertiesTemplate FAILED
Source file /home/csatari/work/dita-ot/config/plugins.xml does not exist

## Steps to Reproduce

1. Clone the repo
2. ./gradlew

## Copy of the error message, log file or stack trace
https://gist.github.com/CsatariGergely/739a5678e9bf7e377e224168de39db3e

## Environment

* DITA-OT version: Upstream master
* Operating system and version:
  Ubuntu 22.04.1 LTS

**Comment by jelovirt** [comment]
Have you built DITA-OT? Where is that?

**Comment by jelovirt** [comment]
This is likely support question, not a bug.

**Comment by infotexture** [comment]
@CsatariGergely It sounds like the Gradle build doesn't know where your installation of DITA Open Toolkit is located.

Did you pass the `ditaHome` option on the command line as described in 
https://github.com/dita-ot/docs#steps ?

```shell
./gradlew -PditaHome=/path/to/dita-ot
```

**Comment by CsatariGergely** [comment]
Oooh, sorry naturally after reading the documentation it is working ;)
