### ISSUE TITLE
Clarify GFM output deltas

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#480]
The info on [Generating Markdown output](https://www.dita-ot.org/dev/topics/dita2markdown.html) currently mentions both `--format=markdown` & `--format=markdown_github`, but doesn't explain the differences when content is output to one format or the other.

IIRC they're subtle (and probably wouldn't justify a separate GFM syntax reference), but we might want to point out the main points, so people know which to choose.

@jelovirt Can you see at a glance from the code what we'd need to explain there, or do I need to generate both & diff the results to gather the deltas and refresh our memory?

**Comment by jelovirt** [comment]
@infotexture The only difference seems to be that because GFM doesn't have support for definition lists, they are [converted](https://github.com/jelovirt/org.lwdita/blob/master/src/main/resources/dita2markdown_github.xsl#L13) to unordered lists with a header. Something like this:

```markdown
*   **Term**
  
    First definition.

    Second definition.
*   **Term**
  
    First definition.

    Second definition.
```

**Comment by infotexture** [comment]
Just compared output and noticed that GFM also omits the Pandoc [header attributes](https://pandoc.org/MANUAL.html#extension-header_attributes).
