### ISSUE TITLE
Variable file in simple PDF plugin example does not affect output

### ISSUE THREAD

**Issue by jdwinfodesign** [dita-ot/docs#482]
## Expected Behavior
When following Step 7 of the [Creating a simple PDF plug-in](https://www.dita-ot.org/dev/topics/pdf-customization-example.html) example (create `cfg/common/vars/en.xml`) list numbers should not have trailing dots; items in unordered list should have em dashes instead of bullets.

## Actual Behavior
The file has no effect. 

Neither does the example in  `docsrc/samples/plugins/com.example.print-pdf/`.

## Possible Solution
Using "Ordered List Number" and "Unordered List bullet" for @id fails; substituted "Ordered List Number 1" and "Unordered List bullet 1" and the changes appear. 

## Steps to Reproduce

1. Download OT
2. Follow the steps 
3. Observe the (lack of) results

## Environment

* DITA-OT version: 4.0
* Windows
* Oxygen
* PDF2

**Comment by infotexture** [comment]
@jdwinfodesign 🙏 Thanks for reporting this Joe.

I was able to reproduce the issue by adding `docsrc/samples/plugins` to the `plugindirs` key in [the configuration.properties file](https://www.dita-ot.org/dev/parameters/configuration-properties-file.html#configuration__plugindirs) and running `dita --install` to install the sample plug-ins, and generating output with the `print-pdf` transtype.

It looks like the `Ordered List Number` and `Unordered List bullet` variables were moved from [cfg/common/vars/en.xml](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/common/vars/en.xml) to [cfg/common/vars/commonvariables.xml](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/common/vars/commonvariables.xml#L91-L107) for DITA-OT 3.0 in dita-ot/dita-ot#2789, so the filename in the sample plug-in needs to be updated accordingly. 

I'll do that now.

**Comment by infotexture** [comment]
Turns out the additional `$depth` parameter was added in dita-ot/dita-ot@48b8e75 for dita-ot/dita-ot#1134, so we need to add the ` 1` to both variable IDs make this work again.
