### ISSUE TITLE
The `gradle` steps in the README don't work when applied to a repo clone

### ISSUE THREAD

**Issue by mjang-forescout** [dita-ot/docs#509]
Tested on Windows 10, using "Git Bash"

## Expected Behavior

I should get a "BUILD SUCCESSFUL" message

## Actual Behavior

Under [Steps](https://github.com/dita-ot/docs#building-the-documentation-output), "Using a repository clone," the command does not work. From this repo's root, when I run:

```
./gradlew -PditaHome=../dita/src/main
```
I get errors including:

Source file: C:\Users\<my username>\Repos\dita-ot\src\main\config\plugins.xml does not exist

## Possible Solution

Optional solutions:

- Exclude the option for using the repo
- Include appropriate files in the repo config\ subdirectly

## Steps to Reproduce

1. Follow the docs, specifically the "Using a repository clone" section

**Comment by infotexture** [comment]
Hi Mike, 

Thanks for trying this out and reporting this issue. I have a hunch what might be wrong here.

Could it be that you recently cloned the DITA-OT core repo, but haven't yet set it up for use as a local toolkit installation? 

The `src\main\config\plugins.xml` file that's mentioned in your error message is not part of the repo, but generated at build time. To create that file and use the repo clone to build output, you'll need to follow the steps in the [Development](https://github.com/dita-ot/dita-ot#development) section of the core repo ReadMe:

> In the root directory, run Gradle to compile the Java code and install plugins:

    ./gradlew

Once you do that, the steps in the docs ReadMe should work.

I think when we wrote those, we were envisioning toolkit developers who were already using their toolkit clone to build output, and just needed to know what to do to build the docs. We probably didn't anticipate the "start from scratch" use case, but should have.

If you confirm that solves the problem in your case, we can improve the instructions to make sure this doesn't happen to anyone else.

**Comment by infotexture** [comment]
@mjang-forescout Are you able to verify whether running Gradle in the core repo solves this for you?

**Comment by mjang-forescout** [comment]
Thanks for responding and following up, @infotexture . 

Your suggestion did work. I assume the `--recurse-submodules` command builds the noted *.xml files in the dita/src/main/config subdirectory

**Comment by mjang-forescout** [comment]
FWIW, I'm using GitBash on Windows 10 -- which requires me to use the "Linux or MacOS" instructions.

**Comment by infotexture** [comment]
> I assume the `--recurse-submodules` command builds the noted *.xml files

It's the Gradle build, not the submodules update, but glad to hear it works for you.

I updated the instructions in the ReadMe to make this clearer.

Thanks again for reporting this. 🙏
