### ISSUE TITLE
HTML Help Workshop no longer available from Microsoft

### ISSUE THREAD

**Issue by super-structure** [dita-ot/docs#536]
## Expected Behavior
Link to prerequisite software should be up-to-date.

## Actual Behavior
The link to download Microsoft's HTML Help Workshop program leads to a page for that program at learn.microsoft.com. However, the link to download the program gives a 404 error (for either the English or Japanese versions). The page itself was last updated almost 6 years ago.

## Possible Solution
If there is a current (and hopefully stable) link to download the HTML Help Workshop, this would be preferable. [This Q&A](https://learn.microsoft.com/en-us/answers/questions/265752/htmlhelp-workshop-download-for-chm-compiler-instal) correctly points out that the installer is still available at archive.org. So this may be an alternative. Also, Divcom software has a download link on the [HelpSmith program downloads page](https://www.helpsmith.com/download.php), as well.

Another response states that they have the installer in a GitHub repo, but there may be some license issues involved with this solution.

## Steps to Reproduce

1. Open the Prerequisite software topic in the DITA-OT docs.
2. Click the link to msdn.microsoft.com. Page redirects to learn.microsoft.com.
3. Click the link to [Download Htmlhelp.exe](https://go.microsoft.com/fwlink/p/?linkid=14188). 404 page is given.

## Copy of the error message, log file or stack trace
Target page: [https://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe](https://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe)

## Environment
Web browser.

* DITA-OT version: n/a
* Operating system and version: n/a
* How did you run DITA-OT? n/a
* Transformation type: n.a

**Comment by infotexture** [comment]
@super-structure 🙏 Thanks for the pointers Jason. Link rot sucks. 😞 

Looks like Redmond missed the memo that [Cool URIs don't change](https://www.w3.org/Provider/Style/URI.html).
