### ISSUE TITLE
DITA-OT 4.2 documentation states that FOP does not support character-by-character font selection strategy when it does

### ISSUE THREAD

**Issue by jusla** [dita-ot/docs#537]
## Expected Behavior
DITA-OT 4.2 documentation does not state that FOP does not support character-by-character font selection strategy.

## Actual Behavior
Documentation states that FOP does not support character-by-character font selection strategy.

FOP 2.9 (which is included in DITA-OT 4.2) now supports this font selection strategy:

https://xmlgraphics.apache.org/fop/2.9/releaseNotes_2.9.html

## Steps to Reproduce
1. Visit https://www.dita-ot.org/4.2/parameters/parameters-pdf#pdf__org.dita.pdf2.i18n.enabled

## Copy of the error message, log file or stack trace
"Enables internationalization (I18N) font processing to provide per-character font selection for FO renderers that do not support the font-selection-strategy property (such as Apache FOP)."

## Environment
* DITA-OT version: 4.2
* Transformation type: PDF

**Comment by infotexture** [comment]
@jusla 🙏 Thanks, good catch.

When we upgraded FOP to 2.9 in DITA-OT 4.2, ~~we~~ **(I!)** didn't think to revise this caveat. Will fix that now.
