### ISSUE TITLE
Redo graphic in Developer Reference

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#54]
The `mainarch.gif` [diagram](https://github.com/dita-ot/docs/blob/develop/dev_ref/images/mainarch.gif) in the [Processing structure](http://www.dita-ot.org/dev/dev_ref/processing-structure.html) topic should be updated to reflect recent changes to the toolkit architecture and prepared in a format such as SVG to ensure optimum quality in all docs output formats.

An editable source file for the diagram should be added to the repository to facilitate future updates.

**Comment by keberlein** [comment]
Until we manage to get this work done, can we do something about how badly the image is rendered in the PDF output? It runs off the page, and about 1/3 of the image is not rendered.

Normally I would modify the PDF customization plug-in to ensure that images that are too large are rendered page width. If we are using the OOB PDF transformation, perhaps we should implement some conditional processing to ensure that the image renders scaled in the PDF output.

**Comment by shaneataylor** [comment]
I could create an SVG version that should render correctly.

I held off offering to do this update because I don't have the info about
what content changes should be made. If someone could add this info on the
ticket, I'll be happy to make those changes as well.

Shane Taylor

**Comment by infotexture** [comment]
Regarding the scaling issue: there's no need for custom PDF plugins or conditional processing logic — we just need to set the `@width` attribute for the image.

**Comment by infotexture** [comment]
Open issues in the existing image:

* `web` target has been renamed
* no `toc` file is generated, but HTML5 cover file
* no reference to additional assets (CSS, images, etc. — copied per Ant properties)
* missing output formats (troff, etc.) 
* placeholder node for custom plug-ins
* stronger emphasis on pre-processing (increase box size or change location, etc.)
