### ISSUE TITLE
Update DITA OT videos topic

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#549]
https://www.dita-ot.org/dev/topics/dita-ot-day-videos

DITA OT Day 2024 recordings are now available:

https://www.oxygenxml.com/events/2024/dita-ot_day.html

**Comment by infotexture** [comment]
@raducoravu 🙇 Thanks!

@lief-erickson has a [script](https://gist.github.com/lief-erickson/4019b6ddf09c154164d4830b0fd6e7e8) that should generate the maps and topic. 🙏

**Comment by infotexture** [comment]
Implemented by @lief-erickson in #550 with additional corrections in eb5d084 & 914ce66.

**Comment by raducoravu** [comment]
And here they are:
https://www.dita-ot.org/dev/topics/dita-ot-day-videos-intro-2024
The timeline seems to be backwards, starting with the last presentations and going to the first ones, also without the author names mentioned.

**Comment by lief-erickson** [comment]
The timeline is irrelevant in my opinion, but we should get author names added. They're in the source. Will investigate.

**Comment by infotexture** [comment]
The [2022 version](https://www.dita-ot.org/dev/topics/dita-ot-day-videos-intro-2022) seems to include a few of the author names, but not all.

It would be easy enough to add those and/or manually re-order the sessions to match the agenda, but not sure if the script was originally intended to sort or add authors.
