### ISSUE TITLE
New possible way of collaboration on the DITA OT Docs

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/docs#564]
This is not a proposed docs change, but more of a new collaboration idea.
The Oxygen Content Fusion platform now has a "Projects" feature allowing it to be used with a GitHub account:
https://fusion.oxygenxml.com/projects
So one for example @infotexture can connect Oxygen Content Fusion to the DITA Open Toolkit docs GitHub account with an access token. Then he can either use the personal workspace to make changes and commit them or create review tasks. He can invite other members as well.

There is a what's new video here:
http://next-oxygenxml.sync.ro/content_fusion/whats_new.html

Feel free to close this issue if you are not interested in this approach.

**Comment by raducoravu** [comment]
From what I discussed internally, for occasional contributors the "Edit this page" approach with WebAuthor and pull requests remains a better approach. The Content Fusion Projects feature would be useful maybe to the main documentation writers, if they commit directly not using pull requests. I will close this issue as it's more about one more way of being able to work on the docs and not about changing the docs in some way.

**Comment by infotexture** [comment]
@raducoravu Thanks for the suggestions, but I think you're right.

Most of us that work on the docs regularly generally prefer editing and building locally, as opposed to working in the browser.
