### ISSUE TITLE
apply-template should be apply-templates in docs

### ISSUE THREAD

**Issue by reifsnid** [dita-ot/docs#570]
https://github.com/dita-ot/docs/blob/63d8e93048bbfb1d8622ed330ff3f408ac3b4f2a/topics/plugin-rewrite-rules.dita#L46C6-L46C27

**Comment by infotexture** [comment]
@reifsnid Thanks Daniel, good catch! 🙏

**Comment by reifsnid** [comment]
Thanks for fixing it so fast @infotexture!
