### ISSUE TITLE
In parameters-base.dita "build-step.*" should be "preprocess.*.skip"

### ISSUE THREAD

**Issue by simonbate** [dita-ot/docs#576]
## Expected Behavior
As documented, `build-step.copy-image="false"` should work. 

## Actual Behavior
It doesn't work, because the parameter has been changed in the OT. Now it should be `preprocess.copy-image.skip`.

## Possible Solution
Modify parameters-base.dita to reflect the actual names of the preprocess skipping parameters.

**Comment by infotexture** [comment]
@simonbate Which version are you on?

According to the [4.1 Release Notes](https://www.dita-ot.org/4.1/release-notes/#v4.1__4181), it's the other way around:

> HTMLHelp has been updated to replace the outdated `preprocess.copy-image.skip` property with the corresponding DITA 4.0 `build-step.copy-image` property for compatibility with recent toolkit versions.

The `parameters-base.dita` file is generated automatically from the latest toolkit code, so the `build-step.copy-image` listing there should be correct.

**Comment by infotexture** [comment]
The `preprocess.*.skip` properties were renamed to `build-step.*` in https://github.com/dita-ot/dita-ot/pull/3851/ for https://github.com/dita-ot/dita-ot/issues/3845, which was included in the DITA-OT 4.0 release.

As of 4.0 the `build-step.*` variants are correct, so closing this as invalid.
