### ISSUE TITLE
SVG is not supported by the image metadata filter

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/docs#65]
Per @jelovirt (and I had noticed this behavior). Users of the toolkit can't rely on the intrinsic height / width of SVG images, but must specify @height / @width in the DITA source, and can't use @scale.

Question: I haven't had success getting height / width for PNG images either for scaling purposes — does the image metadata filter also not support PNGs?

Related to #63

**Comment by infotexture** [comment]
@shaneataylor I've been able to scale PNGs fine, as long as only `@height` or `@width` is specified:  `<image href="path/to/image.png" placement="break" width="14cm"/>`.

The [Implementation-dependent features](http://www.dita-ot.org/dev/user-guide/implementation-dependent-features.html) topic has this to say about scaling:

> If both height and width attributes are given, the image is scaled non-uniformly.
> If the scale attribute is not an unsigned integer, no error or warning is thrown during preprocessing.

We should probably add the SVG caveats there, and provide specific examples of `@scale` values that work (and others users might be inclined to use, but which are not supported).

**Comment by infotexture** [comment]
Verified that SVGs are properly scaled in both HTML & PDF output if either `@height` or `@width` is set, but `@scale` is only respected in PDF output.

According to the spec:

> Allowable values are 50, 60, 70, 80, 90, 100, 110, 120, 140, 160, 180, 200, and -dita-use-conref-target. Some DITA processors or output formats might not be able to support all values.
