### ISSUE TITLE
Description of retain.topic.fo parameter contains back-level info?

### ISSUE THREAD

**Issue by keberlein** [dita-ot/docs#67]
It states "If the configuration property org.dita.pdf2.use-out-temp is set to false, this parameter is ignored."

One can no longer set that property in the configuration.properties file; has it been deprecated or moved to a new location?

It shows up as a PDF transformation parameter in oXygen.

**Comment by shaneataylor** [comment]
I would *hope* that true / false values are always equivalent to yes / no, but it's possible they are not in this case.  I am successfully using the following in my .properties files with DITA-OT 2.2.0:

retain.topic.fo = yes

**Comment by jelovirt** [comment]
In most cases you cannot exchange `true`/`false` values with `yes`/`no`. Also, in most cases the values are case-sensitive.

**Comment by keberlein** [comment]
My questions are: 
- Has the org.dita.pdf2.use-out-temp configuration property been removed from the DITA-OT? If so, we should remove that particular sentence from the description of retain.topic.fo parameter.
- Has the org.dita.pdf2.use-out-temp configuration property become a transformation parameter for PDF? If so, we should document it.

**Comment by jelovirt** [comment]
`retain.topic.fo` is not longer supported. Also, `org.dita.pdf2.use-out-temp` has been removed in 2.1 [https://github.com/dita-ot/dita-ot/issues/1898](#1898)

**Comment by keberlein** [comment]
OK, so we need to modify the PDF parameters topic. What is the new mechanism to ensure that the topic.fo file is retained?

**Comment by jelovirt** [comment]
The FO file is never deleted separate from the rest of the temporary files. If you want to keep the FO file, you need to disable temporary directory deletion with `clean.temp=no`

**Comment by keberlein** [comment]
Sounds as if the correct doc fix is to remove the entire listing for retain.topic.fo from the PDF parameters topic.

**Comment by infotexture** [comment]
@keberlein The parameter listings are generated automatically from the plugins bundled with the distribution packages.

@jelovirt Since the `org.dita.pdf2/plugin.xml` file still includes the `retain.topic.fo` parameter on [Line 40](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/plugin.xml#L40), it still appears in the docs.

I removed the deprecated configuration property in commit 77a822d, so this information will no longer be inserted via conref push when parameter listings are generated.

**Comment by jelovirt** [comment]
The `retain.topic.fo` parameter should have been removed when the support for it was removed, not just deprecated.

**Comment by infotexture** [comment]
@jelovirt OK. Do you want an issue or PR for that?

**Comment by jelovirt** [comment]
@infotexture removed already

**Comment by infotexture** [comment]
@jelovirt Great, thanks. I'll remove the entire entry from `ant-parameters-details.dita` and close this then.
