### ISSUE TITLE
DITA-OT error message topic contains links to the DITA 1.2 specification

### ISSUE THREAD

**Issue by keberlein** [dita-ot/docs#68]
The error message topics contains cross references to DITA 1.2 specification topics. The link text for these cross references is as follows

1. URI-based addressing
1. Conref Push
1. the conkeyref definition

@robander and I should probably discuss where these cross references should now go, since the DITA 1.3 spec was substantially reorganized. Also, we'll now need to point to a specific edition of the standard -- Base edition? All-inclusive edition?

**Comment by infotexture** [comment]
@keberlein @robander 
I linked to the 1.3 equivalents in the **Base** edition for all three cases mentioned above:

1. [URI-based addressing](http://docs.oasis-open.org/dita/dita/v1.3/os/part1-base/archSpec/base/uri-based-addressing.html#uri-based-addressing)
2. [Conref Push](http://docs.oasis-open.org/dita/dita/v1.3/os/part1-base/langRef/attributes/theconactionattribute.html#theconactionattribute)
3. [the conkeyref definition](http://docs.oasis-open.org/dita/dita/v1.3/os/part1-base/langRef/attributes/theconkeyrefattribute.html#theconkeyrefattribute)

Please advise if you think any of these should point elsewhere.

**Comment by robander** [comment]
Sounds perfect.

**Comment by keberlein** [comment]
+1
    
    Best,
      Kris
      
      Kristen James Eberlein
      Chair, OASIS DITA Technical Committee
      Principal consultant, Eberlein Consulting
      www.eberleinconsulting.com
      +1 919 682-2290; kriseberlein (skype)
      
    
    On 4/21/2016 3:44 PM, Robert D Anderson
      wrote:
    
    
      Sounds perfect.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly or view
          it on GitHub

**Comment by infotexture** [comment]
Cherry-picked changes from 4d8590f for inclusion in 2.2.5 maintenance release as 7af68ef.
