### ISSUE TITLE
Rearchitect "Creating plug-ins" chapter"

### ISSUE THREAD

**Issue by keberlein** [dita-ot/docs#75]
This topic cluster contains wonderful content, but the content is sometimes difficult to locate, since task, concept, and reference material is all mixed together. I think it would benefit immensely by following standard principles of task-oriented information development.

I suggest:
- Removing content from the parent topic, so it serves primarily as a container topic.
- Moving conceptual content to concept topics, with titles that reflect their content: "What is a DITA-OT plug-in?", "Benefits of DITA-OT plug-ins", etc. (While this material currently is present, it is scattered. It would be easier for a reader to notice it if it were isolated in topics with titles that would appear in the TOC, bookmarks, and search results.)
- Change the topic type of many of the existing topics (those with gerunds in the title) from reference to task. Recast the content in steps.
- Create a reference topic that lists all the extension points. Currently the information is scattered throughout the various topics. (Could such a topic be generated from the code?)
- Ensure example elements do not contain multiple examples. Move extensive examples to their own topics.

Feedback very welcome.

**Comment by infotexture** [comment]
Suggestions look good to me.

The list of extension points is generated automatically since commit 511b600. 
The output appears under `extension-points/all-extension-points.dita` after the docs build runs.

We need to extend the descriptions of each extension point. That task is logged as #55.

**Comment by infotexture** [comment]
See http://www.dita-ot.org/dev/extension-points/all-extension-points.html for current list.

**Comment by infotexture** [comment]
@keberlein Looks like these changes were implemented in #85.

I think we can close this issue & track any further enhancements in separate issues.
