### ISSUE TITLE
Update Installing / Removing Plugins Topics to Use dita Command

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/docs#76]
As the new `dita` command is easier and more powerful (can install from URL) we should document this as the recommended way to install and remove plugins instead of the ant integrator method.

**Comment by infotexture** [comment]
Yes, the `dita` command approach is definitely the recommended method, and is included in the _User Guide_ variants of these topics, albeit alongside descriptions of the legacy Ant method, for example:
http://www.dita-ot.org/dev/user-guide/plugins-installing.html.

Oddly enough, the _Developer Reference_ also describes the process, but only the legacy Ant approach:
http://www.dita-ot.org/dev/dev_ref/plugins-installing.html.

I see no value in duplicating this content, and suggest we remove the redundant _Extending…_ section from the _User Guide_, and update the corresponding _Developer Reference_ section to describe only the `dita` command approach.

**Comment by infotexture** [comment]
Fixed w/ PR #78 & 76e4ac4.
