### ISSUE TITLE
Add topic on `local.properties` file

### ISSUE THREAD

**Issue by markgif** [dita-ot/docs#81]
I don't know if this applies to later OT versions but this works for 1.7.5 on Windows 7. A local.properties file is mentioned in the docs in reference to using the Antenna House PDF processor. Here is some fleshed out info that would be good in the docs.

I created a text file called local.properties and put it in the 1.7.5 OT root directory. The entire content of the file is this:

axf.path=C:\\Program Files\\Antenna House\\AHFormatterV62

I had to escape the backslashes by repeating them: \\

No quotes around the path were needed, even though there are spaces in it. Adding quotes around the path makes it fail. 

It does not require that you run integrator to make it take effect.

Mark

**Comment by infotexture** [comment]
Thanks for the input. You're right, the docs are a bit sparse with regard to the use of `.properties` files.

We're working on improving this with the changes for #62, which adds info on “[Setting build parameters with .properties files](http://www.dita-ot.org/dev/user-guide/build-using-dita-properties-file.html)”, and #46, which points out missing configuration properties.

We'll add a new topic to explain how the `local.properties` file can be used, and how properties set there interact with those defined via `dita -propertyfile` and `dita -Dparameter=value`.

**Comment by markgif** [comment]
Thanks! I have since also found out about two undocumented command line parameters for enabling the use of Antenna House: 

ahf.dir
The directory where AH is installed.

ahf.cmd
The path to AHFCmd.exe in that directory. (I'm using Windows 7, not sure about other OSes)

You have to escape the backslashes with \\\\, even though the path to the ditamap does not have to use escaped backslashes (arcane!). So the following command seems to work with OT 1.7.5 without the local.properties file as described earlier:

ant -Dargs.input=C:\path\to\map\my.ditamap -Dtranstype=my-pdf -Dpdf.formatter=ah -Dahf.dir=C:\\Program Files\\Antenna House\\AHFormatterV62 -Dahf.cmd=C:\\Program Files\\Antenna House\\AHFormatterV62

**Comment by shaneataylor** [comment]
@markgif I think we addressed the properties file with some doc changes here: http://www.dita-ot.org/2.3/user-guide/build-using-dita-properties-file.html

Let the team know if you're satisfied we've addressed that issue. I opened #101 and #102 to address the other two issues raised here.

Thanks!
