### ISSUE TITLE
Text overruns in "Generate lists" table

### ISSUE THREAD

**Issue by keberlein** [dita-ot/docs#82]
In the "Generate lists (gen-list)" topics, we have a table where the text from one entry overruns the text for the next. It's difficult to read, and it looks very unprofessional.

DITA Open Toolkit Developer Reference > Architecture of the DITA Open Toolkit > Pre-processing modules > Generate lists (gen-list)

I think we need an alternate information design here. Also, is the content up-to-date?

This is not a new problem; it's been around for quite a long time. But maybe with more people involved in the DITA-OT documentation, we can pay some attention to this now.

**Comment by infotexture** [comment]
See #2.
