### ISSUE TITLE
generate.copy.outer documented as generate.outer.copy

### ISSUE THREAD

**Issue by robander** [dita-ot/docs#87]
Felt like I had to double and triple check myself on this one, but the `generate.copy.outer` parameter has a dedicated topic to describe how it works, and throughout that topic it is documented as `generate.outer.copy`. 

The file name still reflects the actual parameter name:
http://www.dita-ot.org/dev/parameters/generate-copy-outer.html

It's listed correctly in the "Common parameters", but you can see the mismatch in the link text that goes to this topic:
http://www.dita-ot.org/dev/parameters/parameters-base.html

Not exactly related but an issue with the same topic -- the dedicated description appears in the map with `toc="no"`, but is still adding a child link to the "HTML-based output parameters" topic. May want to add `linking="no"` as well, or else make it a child of the common parameters topic:
http://www.dita-ot.org/dev/parameters/parameters-base-html.html

**Comment by infotexture** [comment]
Wow, good catch—surprised noone's noticed that yet all these years!

Just checked the Git history for the file, and it appears it's been that way ever since the files were tracked in Git—and so probably longer.

**Comment by robander** [comment]
I suspect it's because any time anybody tries to understand that parameter, their mind melts a little, and they no longer see words.
