### ISSUE TITLE
Explain outputFile.base

### ISSUE THREAD

**Issue by xephon2** [dita-ot/docs#89]
Could you please add `outputFile.base` to [PDF parameters](http://www.dita-ot.org/dev/parameters/parameters-pdf.html)?

```xml
<target name="pdf">
  <dita-ot transtype="pdf" input="userguide-book.ditamap" output="${doc.out.dir}">
    <properties>
      <property name="outputFile.base" value="userguide"/>
      <property name="processing-mode" value="strict"/>
    </properties>
  </dita-ot>
</target>
```

**Comment by keberlein** [comment]
I don't think this is ready to be added to the documentation. See https://github.com/dita-ot/dita-ot/issues/1200
